// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Aggregated metrics for
/// [ShipmentRoute][google.cloud.optimization.v1.ShipmentRoute] (resp. for
/// [OptimizeToursResponse][google.cloud.optimization.v1.OptimizeToursResponse]
/// over all [Transition][google.cloud.optimization.v1.ShipmentRoute.Transition]
/// and/or [Visit][google.cloud.optimization.v1.ShipmentRoute.Visit] (resp. over
/// all [ShipmentRoute][google.cloud.optimization.v1.ShipmentRoute]) elements.
///
/// [google.cloud.optimization.v1.OptimizeToursResponse]: <doc:OptimizeToursResponse>
/// [google.cloud.optimization.v1.ShipmentRoute]: <doc:ShipmentRoute>
/// [google.cloud.optimization.v1.ShipmentRoute.Transition]: <doc:ShipmentRoute/Transition>
/// [google.cloud.optimization.v1.ShipmentRoute.Visit]: <doc:ShipmentRoute/Visit>
public struct AggregatedMetrics: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Number of shipments performed. Note that a pickup and delivery pair only
  /// counts once.
  public var performedShipmentCount: Swift.Int32 = Swift.Int32()

  /// Total travel duration for a route or a solution.
  public var travelDuration: GoogleCloudWKT.Duration? = nil

  /// Total wait duration for a route or a solution.
  public var waitDuration: GoogleCloudWKT.Duration? = nil

  /// Total delay duration for a route or a solution.
  public var delayDuration: GoogleCloudWKT.Duration? = nil

  /// Total break duration for a route or a solution.
  public var breakDuration: GoogleCloudWKT.Duration? = nil

  /// Total visit duration for a route or a solution.
  public var visitDuration: GoogleCloudWKT.Duration? = nil

  /// The total duration should be equal to the sum of all durations above.
  /// For routes, it also corresponds to:
  /// [ShipmentRoute.vehicle_end_time][google.cloud.optimization.v1.ShipmentRoute.vehicle_end_time]
  /// `-`
  /// [ShipmentRoute.vehicle_start_time][google.cloud.optimization.v1.ShipmentRoute.vehicle_start_time]
  ///
  /// [google.cloud.optimization.v1.ShipmentRoute.vehicle_end_time]: <doc:ShipmentRoute/vehicleEndTime>
  /// [google.cloud.optimization.v1.ShipmentRoute.vehicle_start_time]: <doc:ShipmentRoute/vehicleStartTime>
  public var totalDuration: GoogleCloudWKT.Duration? = nil

  /// Total travel distance for a route or a solution.
  public var travelDistanceMeters: Swift.Double = Swift.Double()

  /// Maximum load achieved over the entire route (resp. solution), for each of
  /// the quantities on this route (resp. solution), computed as the maximum over
  /// all
  /// [Transition.vehicle_loads][google.cloud.optimization.v1.ShipmentRoute.Transition.vehicle_loads]
  /// (resp.
  /// [ShipmentRoute.metrics.max_loads][google.cloud.optimization.v1.AggregatedMetrics.max_loads].
  ///
  /// [google.cloud.optimization.v1.AggregatedMetrics.max_loads]: <doc:AggregatedMetrics/maxLoads>
  /// [google.cloud.optimization.v1.ShipmentRoute.Transition.vehicle_loads]: <doc:ShipmentRoute/Transition/vehicleLoads>
  public var maxLoads: [Swift.String: ShipmentRoute.VehicleLoad] = [:]

  /// Deprecated: Use
  /// [ShipmentRoute.route_costs][google.cloud.optimization.v1.ShipmentRoute.route_costs]
  /// and
  /// [OptimizeToursResponse.Metrics.costs][google.cloud.optimization.v1.OptimizeToursResponse.Metrics.costs]
  /// instead.
  ///
  /// [google.cloud.optimization.v1.OptimizeToursResponse.Metrics.costs]: <doc:OptimizeToursResponse/Metrics/costs>
  /// [google.cloud.optimization.v1.ShipmentRoute.route_costs]: <doc:ShipmentRoute/routeCosts>
  @available(*, deprecated)
  public var costs: [Swift.String: Swift.Double] = [:]

  /// Deprecated: Use
  /// [ShipmentRoute.route_total_cost][google.cloud.optimization.v1.ShipmentRoute.route_total_cost]
  /// and
  /// [OptimizeToursResponse.Metrics.total_cost][google.cloud.optimization.v1.OptimizeToursResponse.Metrics.total_cost]
  /// instead.
  ///
  /// [google.cloud.optimization.v1.OptimizeToursResponse.Metrics.total_cost]: <doc:OptimizeToursResponse/Metrics/totalCost>
  /// [google.cloud.optimization.v1.ShipmentRoute.route_total_cost]: <doc:ShipmentRoute/routeTotalCost>
  @available(*, deprecated)
  public var totalCost: Swift.Double = Swift.Double()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `AggregatedMetrics`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AggregatedMetrics().with { $0.performedShipmentCount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let performedShipmentCount = CodingKeys(stringValue: "performedShipmentCount")
    static let travelDuration = CodingKeys(stringValue: "travelDuration")
    static let waitDuration = CodingKeys(stringValue: "waitDuration")
    static let delayDuration = CodingKeys(stringValue: "delayDuration")
    static let breakDuration = CodingKeys(stringValue: "breakDuration")
    static let visitDuration = CodingKeys(stringValue: "visitDuration")
    static let totalDuration = CodingKeys(stringValue: "totalDuration")
    static let travelDistanceMeters = CodingKeys(stringValue: "travelDistanceMeters")
    static let maxLoads = CodingKeys(stringValue: "maxLoads")
    static let costs = CodingKeys(stringValue: "costs")
    static let totalCost = CodingKeys(stringValue: "totalCost")

    static let _knownKeys: Set<Swift.String> = [
      "performedShipmentCount",
      "travelDuration",
      "waitDuration",
      "delayDuration",
      "breakDuration",
      "visitDuration",
      "totalDuration",
      "travelDistanceMeters",
      "maxLoads",
      "costs",
      "totalCost",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .performedShipmentCount)
    {
      self.performedShipmentCount = value
    }
    self.travelDuration = try container.decodeIfPresent(
      GoogleCloudWKT.Duration.self, forKey: .travelDuration)
    self.waitDuration = try container.decodeIfPresent(
      GoogleCloudWKT.Duration.self, forKey: .waitDuration)
    self.delayDuration = try container.decodeIfPresent(
      GoogleCloudWKT.Duration.self, forKey: .delayDuration)
    self.breakDuration = try container.decodeIfPresent(
      GoogleCloudWKT.Duration.self, forKey: .breakDuration)
    self.visitDuration = try container.decodeIfPresent(
      GoogleCloudWKT.Duration.self, forKey: .visitDuration)
    self.totalDuration = try container.decodeIfPresent(
      GoogleCloudWKT.Duration.self, forKey: .totalDuration)
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .travelDistanceMeters) {
      self.travelDistanceMeters = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: ShipmentRoute.VehicleLoad].self, forKey: .maxLoads)
    {
      self.maxLoads = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.Double].self, forKey: .costs)
    {
      self.costs = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .totalCost) {
      self.totalCost = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.performedShipmentCount, forKey: .performedShipmentCount)
    try container.encodeIfPresent(self.travelDuration, forKey: .travelDuration)
    try container.encodeIfPresent(self.waitDuration, forKey: .waitDuration)
    try container.encodeIfPresent(self.delayDuration, forKey: .delayDuration)
    try container.encodeIfPresent(self.breakDuration, forKey: .breakDuration)
    try container.encodeIfPresent(self.visitDuration, forKey: .visitDuration)
    try container.encodeIfPresent(self.totalDuration, forKey: .totalDuration)
    try container.encode(self.travelDistanceMeters, forKey: .travelDistanceMeters)
    try container.encode(self.maxLoads, forKey: .maxLoads)
    try container.encode(self.costs, forKey: .costs)
    try container.encode(self.totalCost, forKey: .totalCost)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.AggregatedMetrics"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
