// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request to batch optimize tours as an asynchronous operation.
/// Each input file should contain one `OptimizeToursRequest`, and each output
/// file will contain one `OptimizeToursResponse`. The request contains
/// information to read/write and parse the files. All the input and output files
/// should be under the same project.
public struct BatchOptimizeToursRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Target project and location to make a call.
  ///
  /// Format: `projects/{project-id}/locations/{location-id}`.
  ///
  /// If no location is specified, a region will be chosen automatically.
  public var parent: Swift.String = Swift.String()

  /// Required. Input/Output information each purchase model, such as file paths
  /// and data formats.
  public var modelConfigs: [BatchOptimizeToursRequest.AsyncModelConfig] = []

  /// Initialize a new instance of `BatchOptimizeToursRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchOptimizeToursRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Information for solving one optimization model asynchronously.
  public struct AsyncModelConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// User defined model name, can be used as alias by users to keep track of
    /// models.
    public var displayName: Swift.String = Swift.String()

    /// Required. Information about the input model.
    public var inputConfig: InputConfig? = nil

    /// Required. The desired output location information.
    public var outputConfig: OutputConfig? = nil

    /// If this is set, the model will be solved in the checkpoint mode. In this
    /// mode, the input model can have a deadline longer than 30 mins without the
    /// risk of interruption. The model will be solved in multiple short-running
    /// stages. Each stage generates an intermediate checkpoint
    /// and stores it in the user's Cloud Storage buckets. The checkpoint
    /// mode should be preferred over
    /// allow_large_deadline_despite_interruption_risk since it prevents the risk
    /// of interruption.
    public var enableCheckpoints: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `AsyncModelConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AsyncModelConfig().with { $0.displayName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.optimization.v1.BatchOptimizeToursRequest.AsyncModelConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.BatchOptimizeToursRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
