// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Rules to generate time breaks for a vehicle (e.g. lunch breaks). A break
/// is a contiguous period of time during which the vehicle remains idle at its
/// current position and cannot perform any visit. A break may occur:
///
/// * during the travel between two visits (which includes the time right
///   before or right after a visit, but not in the middle of a visit), in
///   which case it extends the corresponding transit time between the visits,
/// * or before the vehicle start (the vehicle may not start in the middle of
///   a break), in which case it does not affect the vehicle start time.
/// * or after the vehicle end (ditto, with the vehicle end time).
public struct BreakRule: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Sequence of breaks. See the `BreakRequest` message.
  public var breakRequests: [BreakRule.BreakRequest] = []

  /// Several `FrequencyConstraint` may apply. They must all be satisfied by
  /// the `BreakRequest`s of this `BreakRule`. See `FrequencyConstraint`.
  public var frequencyConstraints: [BreakRule.FrequencyConstraint] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `BreakRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BreakRule().with { $0.breakRequests = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let breakRequests = CodingKeys(stringValue: "breakRequests")
    static let frequencyConstraints = CodingKeys(stringValue: "frequencyConstraints")

    static let _knownKeys: Set<Swift.String> = [
      "breakRequests",
      "frequencyConstraints",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [BreakRule.BreakRequest].self, forKey: .breakRequests)
    {
      self.breakRequests = value
    }
    if let value = try container.decodeIfPresent(
      [BreakRule.FrequencyConstraint].self, forKey: .frequencyConstraints)
    {
      self.frequencyConstraints = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.breakRequests, forKey: .breakRequests)
    try container.encode(self.frequencyConstraints, forKey: .frequencyConstraints)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The sequence of breaks (i.e. their number and order) that apply to each
  /// vehicle must be known beforehand. The repeated `BreakRequest`s define
  /// that sequence, in the order in which they must occur. Their time windows
  /// (`earliest_start_time` / `latest_start_time`) may overlap, but they must
  /// be compatible with the order (this is checked).
  public struct BreakRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Lower bound (inclusive) on the start of the break.
    public var earliestStartTime: GoogleCloudWKT.Timestamp? = nil

    /// Required. Upper bound (inclusive) on the start of the break.
    public var latestStartTime: GoogleCloudWKT.Timestamp? = nil

    /// Required. Minimum duration of the break. Must be positive.
    public var minDuration: GoogleCloudWKT.Duration? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `BreakRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BreakRequest().with { $0.earliestStartTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let earliestStartTime = CodingKeys(stringValue: "earliestStartTime")
      static let latestStartTime = CodingKeys(stringValue: "latestStartTime")
      static let minDuration = CodingKeys(stringValue: "minDuration")

      static let _knownKeys: Set<Swift.String> = [
        "earliestStartTime",
        "latestStartTime",
        "minDuration",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.earliestStartTime = try container.decodeIfPresent(
        GoogleCloudWKT.Timestamp.self, forKey: .earliestStartTime)
      self.latestStartTime = try container.decodeIfPresent(
        GoogleCloudWKT.Timestamp.self, forKey: .latestStartTime)
      self.minDuration = try container.decodeIfPresent(
        GoogleCloudWKT.Duration.self, forKey: .minDuration)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.earliestStartTime, forKey: .earliestStartTime)
      try container.encodeIfPresent(self.latestStartTime, forKey: .latestStartTime)
      try container.encodeIfPresent(self.minDuration, forKey: .minDuration)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.BreakRule.BreakRequest"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// One may further constrain the frequency and duration of the breaks
  /// specified above, by enforcing a minimum break frequency, such as
  /// "There must be a break of at least 1 hour every 12 hours". Assuming that
  /// this can be interpreted as "Within any sliding time window of 12h, there
  /// must be at least one break of at least one hour", that example would
  /// translate to the following `FrequencyConstraint`:
  /// ```
  /// {
  ///    min_break_duration { seconds: 3600 }         # 1 hour.
  ///    max_inter_break_duration { seconds: 39600 }  # 11 hours (12 - 1 = 11).
  /// }
  /// ```
  ///
  /// The timing and duration of the breaks in the solution will respect all
  /// such constraints, in addition to the time windows and minimum durations
  /// already specified in the `BreakRequest`.
  ///
  /// A `FrequencyConstraint` may in practice apply to non-consecutive breaks.
  /// For example, the following schedule honors the "1h every 12h" example:
  /// ```
  ///   04:00 vehicle start
  ///    .. performing travel and visits ..
  ///   09:00 1 hour break
  ///   10:00 end of the break
  ///    .. performing travel and visits ..
  ///   12:00 20-min lunch break
  ///   12:20 end of the break
  ///    .. performing travel and visits ..
  ///   21:00 1 hour break
  ///   22:00 end of the break
  ///    .. performing travel and visits ..
  ///   23:59 vehicle end
  /// ```
  public struct FrequencyConstraint: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Minimum break duration for this constraint. Nonnegative.
    /// See description of `FrequencyConstraint`.
    public var minBreakDuration: GoogleCloudWKT.Duration? = nil

    /// Required. Maximum allowed span of any interval of time in the route that
    /// does not include at least partially a break of `duration >=
    /// min_break_duration`. Must be positive.
    public var maxInterBreakDuration: GoogleCloudWKT.Duration? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `FrequencyConstraint`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FrequencyConstraint().with { $0.minBreakDuration = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let minBreakDuration = CodingKeys(stringValue: "minBreakDuration")
      static let maxInterBreakDuration = CodingKeys(stringValue: "maxInterBreakDuration")

      static let _knownKeys: Set<Swift.String> = [
        "minBreakDuration",
        "maxInterBreakDuration",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.minBreakDuration = try container.decodeIfPresent(
        GoogleCloudWKT.Duration.self, forKey: .minBreakDuration)
      self.maxInterBreakDuration = try container.decodeIfPresent(
        GoogleCloudWKT.Duration.self, forKey: .maxInterBreakDuration)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.minBreakDuration, forKey: .minBreakDuration)
      try container.encodeIfPresent(self.maxInterBreakDuration, forKey: .maxInterBreakDuration)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.BreakRule.FrequencyConstraint"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.BreakRule"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
