// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A limit defining a maximum distance which can be traveled. It can be either
/// hard or soft.
///
/// If a soft limit is defined, both `soft_max_meters` and
/// `cost_per_kilometer_above_soft_max` must be defined and be nonnegative.
public struct DistanceLimit: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// A hard limit constraining the distance to be at most max_meters. The limit
  /// must be nonnegative.
  public var maxMeters: Swift.Int64? = nil

  /// A soft limit not enforcing a maximum distance limit, but when violated
  /// results in a cost which adds up to other costs defined in the model,
  /// with the same unit.
  ///
  /// If defined soft_max_meters must be less than max_meters and must be
  /// nonnegative.
  public var softMaxMeters: Swift.Int64? = nil

  /// Cost per kilometer incurred, increasing up to `soft_max_meters`, with
  /// formula:
  /// ```
  ///   min(distance_meters, soft_max_meters) / 1000.0 *
  ///   cost_per_kilometer_below_soft_max.
  /// ```
  /// This cost is not supported in `route_distance_limit`.
  public var costPerKilometerBelowSoftMax: Swift.Double? = nil

  /// Cost per kilometer incurred if distance is above `soft_max_meters` limit.
  /// The additional cost is 0 if the distance is under the limit, otherwise the
  /// formula used to compute the cost is the following:
  /// ```
  ///   (distance_meters - soft_max_meters) / 1000.0 *
  ///   cost_per_kilometer_above_soft_max.
  /// ```
  /// The cost must be nonnegative.
  public var costPerKilometerAboveSoftMax: Swift.Double? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `DistanceLimit`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DistanceLimit().with { $0.maxMeters = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let maxMeters = CodingKeys(stringValue: "maxMeters")
    static let softMaxMeters = CodingKeys(stringValue: "softMaxMeters")
    static let costPerKilometerBelowSoftMax = CodingKeys(
      stringValue: "costPerKilometerBelowSoftMax")
    static let costPerKilometerAboveSoftMax = CodingKeys(
      stringValue: "costPerKilometerAboveSoftMax")

    static let _knownKeys: Set<Swift.String> = [
      "maxMeters",
      "softMaxMeters",
      "costPerKilometerBelowSoftMax",
      "costPerKilometerAboveSoftMax",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.maxMeters = try container.decodeIfPresent(Swift.Int64.self, forKey: .maxMeters)
    self.softMaxMeters = try container.decodeIfPresent(Swift.Int64.self, forKey: .softMaxMeters)
    self.costPerKilometerBelowSoftMax = try container.decodeIfPresent(
      Swift.Double.self, forKey: .costPerKilometerBelowSoftMax)
    self.costPerKilometerAboveSoftMax = try container.decodeIfPresent(
      Swift.Double.self, forKey: .costPerKilometerAboveSoftMax)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.maxMeters, forKey: .maxMeters)
    try container.encodeIfPresent(self.softMaxMeters, forKey: .softMaxMeters)
    try container.encodeIfPresent(
      self.costPerKilometerBelowSoftMax, forKey: .costPerKilometerBelowSoftMax)
    try container.encodeIfPresent(
      self.costPerKilometerAboveSoftMax, forKey: .costPerKilometerAboveSoftMax)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.DistanceLimit"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
