// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// A service for optimizing vehicle tours.
///
/// Validity of certain types of fields:
///
///   * `google.protobuf.Timestamp`
///     * Times are in Unix time: seconds since 1970-01-01T00:00:00+00:00.
///     * seconds must be in [0, 253402300799],
///       i.e. in [1970-01-01T00:00:00+00:00, 9999-12-31T23:59:59+00:00].
///     * nanos must be unset or set to 0.
///   * `google.protobuf.Duration`
///     * seconds must be in [0, 253402300799],
///       i.e. in [1970-01-01T00:00:00+00:00, 9999-12-31T23:59:59+00:00].
///     * nanos must be unset or set to 0.
///   * `google.type.LatLng`
///     * latitude must be in [-90.0, 90.0].
///     * longitude must be in [-180.0, 180.0].
///     * at least one of latitude and longitude must be non-zero.
///
/// @Snippet(path: "FleetRoutingQuickstart")
public class FleetRoutingClient: Clients.FleetRoutingProtocol {
  let inner: any Clients.FleetRoutingStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `FleetRoutingClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.FleetRoutingStub = try Clients.FleetRoutingTransport(options)
    inner = Clients.FleetRoutingRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.FleetRoutingLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Sends an `OptimizeToursRequest` containing a `ShipmentModel` and returns an
  /// `OptimizeToursResponse` containing `ShipmentRoute`s, which are a set of
  /// routes to be performed by vehicles minimizing the overall cost.
  ///
  /// A `ShipmentModel` model consists mainly of `Shipment`s that need to be
  /// carried out and `Vehicle`s that can be used to transport the `Shipment`s.
  /// The `ShipmentRoute`s assign `Shipment`s to `Vehicle`s. More specifically,
  /// they assign a series of `Visit`s to each vehicle, where a `Visit`
  /// corresponds to a `VisitRequest`, which is a pickup or delivery for a
  /// `Shipment`.
  ///
  /// The goal is to provide an assignment of `ShipmentRoute`s to `Vehicle`s that
  /// minimizes the total cost where cost has many components defined in the
  /// `ShipmentModel`.
  ///
  /// @Snippet(path: "FleetRouting_OptimizeTours")
  public func optimizeTours(
    request: OptimizeToursRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOptimizationV1.OptimizeToursResponse {
    try await self.inner.optimizeTours(request: request, options: options)
  }

  /// Optimizes vehicle tours for one or more `OptimizeToursRequest`
  /// messages as a batch.
  ///
  /// This method is a Long Running Operation (LRO). The inputs for optimization
  /// (`OptimizeToursRequest` messages) and outputs (`OptimizeToursResponse`
  /// messages) are read/written from/to Cloud Storage in user-specified
  /// format. Like the `OptimizeTours` method, each `OptimizeToursRequest`
  /// contains a `ShipmentModel` and returns an `OptimizeToursResponse`
  /// containing `ShipmentRoute`s, which are a set of routes to be performed by
  /// vehicles minimizing the overall cost.
  ///
  /// @Snippet(path: "FleetRouting_BatchOptimizeTours")
  public func batchOptimizeTours(
    request: BatchOptimizeToursRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.batchOptimizeTours(request: request, options: options)
  }

  /// Optimizes vehicle tours for one or more `OptimizeToursRequest`
  /// messages as a batch.
  ///
  /// This method is a Long Running Operation (LRO). The inputs for optimization
  /// (`OptimizeToursRequest` messages) and outputs (`OptimizeToursResponse`
  /// messages) are read/written from/to Cloud Storage in user-specified
  /// format. Like the `OptimizeTours` method, each `OptimizeToursRequest`
  /// contains a `ShipmentModel` and returns an `OptimizeToursResponse`
  /// containing `ShipmentRoute`s, which are a set of routes to be performed by
  /// vehicles minimizing the overall cost.
  ///
  /// @Snippet(path: "FleetRouting_BatchOptimizeTours")
  public func batchOptimizeTours(
    withPolling: BatchOptimizeToursRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<BatchOptimizeToursResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<BatchOptimizeToursResponse>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try BatchOptimizeToursResponse(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.batchOptimizeTours(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<BatchOptimizeToursResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "FleetRouting_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `FleetRoutingClient`.
  ///
  /// To mock `FleetRoutingClient` change your functions to receive
  /// `some FleetRoutingProtocol` or `any FleetRoutingProtocol`
  /// and pass a mock implementation in your tests.
  public protocol FleetRoutingProtocol {
    /// See `FleetRoutingClient.optimizeTours`.
    func optimizeTours(request: OptimizeToursRequest) async throws
      -> GoogleCloudOptimizationV1.OptimizeToursResponse

    /// See `FleetRoutingClient.batchOptimizeTours`.
    func batchOptimizeTours(request: BatchOptimizeToursRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `FleetRoutingClient.batchOptimizeTours`.
    func batchOptimizeTours(withPolling: BatchOptimizeToursRequest) async throws
      -> any GoogleCloudGax.PollableOperation<BatchOptimizeToursResponse>

    /// See `FleetRoutingClient.optimizeTours`.
    func optimizeTours(
      request: OptimizeToursRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOptimizationV1.OptimizeToursResponse

    /// See `FleetRoutingClient.batchOptimizeTours`.
    func batchOptimizeTours(
      request: BatchOptimizeToursRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `FleetRoutingClient.batchOptimizeTours`.
    func batchOptimizeTours(
      withPolling: BatchOptimizeToursRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<BatchOptimizeToursResponse>
  }
}

// Default implementations
extension Clients.FleetRoutingProtocol {
  public func optimizeTours(request: OptimizeToursRequest) async throws
    -> GoogleCloudOptimizationV1.OptimizeToursResponse
  {
    try await self.optimizeTours(request: request, options: .init())
  }

  public func optimizeTours(
    request: OptimizeToursRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOptimizationV1.OptimizeToursResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func batchOptimizeTours(request: BatchOptimizeToursRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.batchOptimizeTours(request: request, options: .init())
  }

  public func batchOptimizeTours(
    request: BatchOptimizeToursRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func batchOptimizeTours(withPolling: BatchOptimizeToursRequest) async throws
    -> any GoogleCloudGax.PollableOperation<BatchOptimizeToursResponse>
  {
    try await self.batchOptimizeTours(withPolling: withPolling, options: .init())
  }

  public func batchOptimizeTours(
    withPolling: BatchOptimizeToursRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<BatchOptimizeToursResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<BatchOptimizeToursResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
