// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Solution injected in the request including information about which visits
/// must be constrained and how they must be constrained.
public struct InjectedSolutionConstraint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Routes of the solution to inject. Some routes may be omitted from the
  /// original solution. The routes and skipped shipments must satisfy the basic
  /// validity assumptions listed for `injected_first_solution_routes`.
  public var routes: [ShipmentRoute] = []

  /// Skipped shipments of the solution to inject. Some may be omitted from the
  /// original solution. See the `routes` field.
  public var skippedShipments: [SkippedShipment] = []

  /// For zero or more groups of vehicles, specifies when and how much to relax
  /// constraints. If this field is empty, all non-empty vehicle routes are
  /// fully constrained.
  public var constraintRelaxations: [InjectedSolutionConstraint.ConstraintRelaxation] = []

  /// Initialize a new instance of `InjectedSolutionConstraint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InjectedSolutionConstraint().with { $0.routes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// For a group of vehicles, specifies at what threshold(s) constraints on
  /// visits will be relaxed and to which level. Shipments listed in
  /// the `skipped_shipment` field are constrained to be skipped; i.e., they
  /// cannot be performed.
  public struct ConstraintRelaxation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// All the visit constraint relaxations that will apply to visits on
    /// routes with vehicles in `vehicle_indices`.
    public var relaxations: [InjectedSolutionConstraint.ConstraintRelaxation.Relaxation] = []

    /// Specifies the vehicle indices to which the visit constraint
    /// `relaxations` apply. If empty, this is considered the default and the
    /// `relaxations` apply to all vehicles that are not specified in other
    /// `constraint_relaxations`. There can be at most one default, i.e., at
    /// most one constraint relaxation field is allowed empty
    /// `vehicle_indices`. A vehicle index can only be listed once, even within
    /// several `constraint_relaxations`.
    ///
    /// A vehicle index is mapped the same as
    /// [ShipmentRoute.vehicle_index][google.cloud.optimization.v1.ShipmentRoute.vehicle_index],
    /// if `interpret_injected_solutions_using_labels` is true (see `fields`
    /// comment).
    ///
    /// [google.cloud.optimization.v1.ShipmentRoute.vehicle_index]: <doc:ShipmentRoute/vehicleIndex>
    public var vehicleIndices: [Swift.Int32] = []

    /// Initialize a new instance of `ConstraintRelaxation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConstraintRelaxation().with { $0.relaxations = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// If `relaxations` is empty, the start time and sequence of all visits
    /// on `routes` are fully constrained and no new visits may be inserted or
    /// added to those routes. Also, a vehicle's start and end time in
    /// `routes` is fully constrained, unless the vehicle is empty (i.e., has no
    /// visits and has `used_if_route_is_empty` set to false in the model).
    ///
    /// `relaxations(i).level` specifies the constraint relaxation level applied
    /// to a visit #j that satisfies:
    ///
    ///   * `route.visits(j).start_time >= relaxations(i).threshold_time` AND
    ///   * `j + 1 >= relaxations(i).threshold_visit_count`
    ///
    /// Similarly, the vehicle start is relaxed to `relaxations(i).level` if it
    /// satisfies:
    ///
    ///   * `vehicle_start_time >= relaxations(i).threshold_time` AND
    ///   * `relaxations(i).threshold_visit_count == 0`
    /// and the vehicle end is relaxed to `relaxations(i).level` if it satisfies:
    ///   * `vehicle_end_time >= relaxations(i).threshold_time` AND
    ///   * `route.visits_size() + 1 >= relaxations(i).threshold_visit_count`
    ///
    /// To apply a relaxation level if a visit meets the `threshold_visit_count`
    /// OR the `threshold_time` add two `relaxations` with the same `level`:
    /// one with only `threshold_visit_count` set and the other with only
    /// `threshold_time` set. If a visit satisfies the conditions of multiple
    /// `relaxations`, the most relaxed level applies. As a result, from the
    /// vehicle start through the route visits in order to the vehicle end, the
    /// relaxation level becomes more relaxed: i.e., the relaxation level is
    /// non-decreasing as the route progresses.
    ///
    /// The timing and sequence of route visits that do not satisfy the
    /// threshold conditions of any `relaxations` are fully constrained
    /// and no visits may be inserted into these sequences. Also, if a
    /// vehicle start or end does not satisfy the conditions of any
    /// relaxation the time is fixed, unless the vehicle is empty.
    public struct Relaxation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// The constraint relaxation level that applies when the conditions
      /// at or after `threshold_time` AND at least `threshold_visit_count` are
      /// satisfied.
      public var level: InjectedSolutionConstraint.ConstraintRelaxation.Relaxation.Level =
        InjectedSolutionConstraint.ConstraintRelaxation.Relaxation.Level()

      /// The time at or after which the relaxation `level` may be applied.
      public var thresholdTime: GoogleCloudWkt.Timestamp? = nil

      /// The number of visits at or after which the relaxation `level` may be
      /// applied. If `threshold_visit_count` is 0 (or unset), the `level` may be
      /// applied directly at the vehicle start.
      ///
      /// If it is `route.visits_size() + 1`, the `level` may only be applied to
      /// the vehicle end. If it is more than `route.visits_size() + 1`,
      /// `level` is not applied at all for that route.
      public var thresholdVisitCount: Swift.Int32 = Swift.Int32()

      /// Initialize a new instance of `Relaxation`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Relaxation().with { $0.level = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      /// Expresses the different constraint relaxation levels, which are
      /// applied for a visit and those that follow when it satisfies the
      /// threshold conditions.
      ///
      /// The enumeration below is in order of increasing relaxation.
      public enum Level: Codable, Equatable, Sendable {
        /// Implicit default relaxation level: no constraints are relaxed,
        /// i.e., all visits are fully constrained.
        ///
        /// This value must not be explicitly used in `level`.
        case unspecified
        /// Visit start times and vehicle start/end times will be relaxed, but
        /// each visit remains bound to the same vehicle and the visit sequence
        /// must be observed: no visit can be inserted between them or before
        /// them.
        case relaxVisitTimesAfterThreshold
        /// Same as `RELAX_VISIT_TIMES_AFTER_THRESHOLD`, but the visit sequence
        /// is also relaxed: visits can only be performed by this vehicle, but
        /// can potentially become unperformed.
        case relaxVisitTimesAndSequenceAfterThreshold
        /// Same as `RELAX_VISIT_TIMES_AND_SEQUENCE_AFTER_THRESHOLD`, but the
        /// vehicle is also relaxed: visits are completely free at or after the
        /// threshold time and can potentially become unperformed.
        case relaxAllAfterThreshold
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .relaxVisitTimesAfterThreshold: return 1
          case .relaxVisitTimesAndSequenceAfterThreshold: return 2
          case .relaxAllAfterThreshold: return 3
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "LEVEL_UNSPECIFIED"
          case .relaxVisitTimesAfterThreshold: return "RELAX_VISIT_TIMES_AFTER_THRESHOLD"
          case .relaxVisitTimesAndSequenceAfterThreshold:
            return "RELAX_VISIT_TIMES_AND_SEQUENCE_AFTER_THRESHOLD"
          case .relaxAllAfterThreshold: return "RELAX_ALL_AFTER_THRESHOLD"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Level/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "LEVEL_UNSPECIFIED": self = .unspecified
          case "RELAX_VISIT_TIMES_AFTER_THRESHOLD": self = .relaxVisitTimesAfterThreshold
          case "RELAX_VISIT_TIMES_AND_SEQUENCE_AFTER_THRESHOLD":
            self = .relaxVisitTimesAndSequenceAfterThreshold
          case "RELAX_ALL_AFTER_THRESHOLD": self = .relaxAllAfterThreshold
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Level/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .relaxVisitTimesAfterThreshold
          case 2: self = .relaxVisitTimesAndSequenceAfterThreshold
          case 3: self = .relaxAllAfterThreshold
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode(0)
          case .relaxVisitTimesAfterThreshold: return try container.encode(1)
          case .relaxVisitTimesAndSequenceAfterThreshold: return try container.encode(2)
          case .relaxAllAfterThreshold: return try container.encode(3)
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.optimization.v1.InjectedSolutionConstraint.ConstraintRelaxation.Relaxation"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.optimization.v1.InjectedSolutionConstraint.ConstraintRelaxation"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.InjectedSolutionConstraint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
