// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Response after solving a tour optimization problem containing the routes
/// followed by each vehicle, the shipments which have been skipped and the
/// overall cost of the solution.
public struct OptimizeToursResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Routes computed for each vehicle; the i-th route corresponds to the i-th
  /// vehicle in the model.
  public var routes: [ShipmentRoute] = []

  /// Copy of the
  /// [OptimizeToursRequest.label][google.cloud.optimization.v1.OptimizeToursRequest.label],
  /// if a label was specified in the request.
  ///
  /// [google.cloud.optimization.v1.OptimizeToursRequest.label]: <doc:OptimizeToursRequest/label>
  public var requestLabel: Swift.String = Swift.String()

  /// The list of all shipments skipped.
  public var skippedShipments: [SkippedShipment] = []

  /// List of all the validation errors that we were able to detect
  /// independently. See the "MULTIPLE ERRORS" explanation for the
  /// [OptimizeToursValidationError][google.cloud.optimization.v1.OptimizeToursValidationError]
  /// message.
  ///
  /// [google.cloud.optimization.v1.OptimizeToursValidationError]: <doc:OptimizeToursValidationError>
  public var validationErrors: [OptimizeToursValidationError] = []

  /// Duration, distance and usage metrics for this solution.
  public var metrics: OptimizeToursResponse.Metrics? = nil

  /// Deprecated: Use
  /// [Metrics.total_cost][google.cloud.optimization.v1.OptimizeToursResponse.Metrics.total_cost]
  /// instead. Total cost of the solution. This takes into account all costs:
  /// costs per per hour and travel hour, fixed vehicle costs, unperformed
  /// shipment penalty costs, global duration cost, etc.
  ///
  /// [google.cloud.optimization.v1.OptimizeToursResponse.Metrics.total_cost]: <doc:OptimizeToursResponse/Metrics/totalCost>
  @available(*, deprecated)
  public var totalCost: Swift.Double = Swift.Double()

  /// Initialize a new instance of `OptimizeToursResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OptimizeToursResponse().with { $0.routes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Overall metrics, aggregated over all routes.
  public struct Metrics: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Aggregated over the routes. Each metric is the sum (or max, for loads)
    /// over all
    /// [ShipmentRoute.metrics][google.cloud.optimization.v1.ShipmentRoute.metrics]
    /// fields of the same name.
    ///
    /// [google.cloud.optimization.v1.ShipmentRoute.metrics]: <doc:ShipmentRoute/metrics>
    public var aggregatedRouteMetrics: AggregatedMetrics? = nil

    /// Number of mandatory shipments skipped.
    public var skippedMandatoryShipmentCount: Swift.Int32 = Swift.Int32()

    /// Number of vehicles used. Note: if a vehicle route is empty and
    /// [Vehicle.used_if_route_is_empty][google.cloud.optimization.v1.Vehicle.used_if_route_is_empty]
    /// is true, the vehicle is considered used.
    ///
    /// [google.cloud.optimization.v1.Vehicle.used_if_route_is_empty]: <doc:Vehicle/usedIfRouteIsEmpty>
    public var usedVehicleCount: Swift.Int32 = Swift.Int32()

    /// The earliest start time for a used vehicle, computed as the minimum over
    /// all used vehicles of
    /// [ShipmentRoute.vehicle_start_time][google.cloud.optimization.v1.ShipmentRoute.vehicle_start_time].
    ///
    /// [google.cloud.optimization.v1.ShipmentRoute.vehicle_start_time]: <doc:ShipmentRoute/vehicleStartTime>
    public var earliestVehicleStartTime: GoogleCloudWkt.Timestamp? = nil

    /// The latest end time for a used vehicle, computed as the maximum over all
    /// used vehicles of
    /// [ShipmentRoute.vehicle_end_time][google.cloud.optimization.v1.ShipmentRoute.vehicle_end_time].
    ///
    /// [google.cloud.optimization.v1.ShipmentRoute.vehicle_end_time]: <doc:ShipmentRoute/vehicleEndTime>
    public var latestVehicleEndTime: GoogleCloudWkt.Timestamp? = nil

    /// Cost of the solution, broken down by cost-related request fields.
    /// The keys are proto paths, relative to the input OptimizeToursRequest,
    /// e.g. "model.shipments.pickups.cost", and the values are the total cost
    /// generated by the corresponding cost field, aggregated over the whole
    /// solution. In other words, costs["model.shipments.pickups.cost"] is the
    /// sum of all pickup costs over the solution. All costs defined in the model
    /// are reported in detail here with the exception of costs related to
    /// TransitionAttributes that are only reported in an aggregated way as of
    /// 2022/01.
    public var costs: [Swift.String: Swift.Double] = [:]

    /// Total cost of the solution. The sum of all values in the costs map.
    public var totalCost: Swift.Double = Swift.Double()

    /// Initialize a new instance of `Metrics`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Metrics().with { $0.aggregatedRouteMetrics = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.OptimizeToursResponse.Metrics"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.OptimizeToursResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
