// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request to be given to a tour optimization solver which defines the
/// shipment model to solve as well as optimization parameters.
public struct OptimizeToursRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Target project and location to make a call.
  ///
  /// Format: `projects/{project-id}/locations/{location-id}`.
  ///
  /// If no location is specified, a region will be chosen automatically.
  public var parent: Swift.String = Swift.String()

  /// If this timeout is set, the server returns a response before the timeout
  /// period has elapsed or the server deadline for synchronous requests is
  /// reached, whichever is sooner.
  ///
  /// For asynchronous requests, the server will generate a solution (if
  /// possible) before the timeout has elapsed.
  public var timeout: GoogleCloudWkt.Duration? = nil

  /// Shipment model to solve.
  public var model: ShipmentModel? = nil

  /// By default, the solving mode is `DEFAULT_SOLVE` (0).
  public var solvingMode: OptimizeToursRequest.SolvingMode = OptimizeToursRequest.SolvingMode()

  /// Search mode used to solve the request.
  public var searchMode: OptimizeToursRequest.SearchMode = OptimizeToursRequest.SearchMode()

  /// Guide the optimization algorithm in finding a first solution that is
  /// similar to a previous solution.
  ///
  /// The model is constrained when the first solution is built.
  /// Any shipments not performed on a route are implicitly skipped in the first
  /// solution, but they may be performed in successive solutions.
  ///
  /// The solution must satisfy some basic validity assumptions:
  ///
  ///   * for all routes, `vehicle_index` must be in range and not be duplicated.
  ///   * for all visits, `shipment_index` and `visit_request_index` must be
  ///     in range.
  ///   * a shipment may only be referenced on one route.
  ///   * the pickup of a pickup-delivery shipment must be performed before
  ///     the delivery.
  ///   * no more than one pickup alternative or delivery alternative of
  ///     a shipment may be performed.
  ///   * for all routes, times are increasing (i.e., `vehicle_start_time
  ///     <= visits[0].start_time <= visits[1].start_time ...
  ///     <= vehicle_end_time`).
  ///   * a shipment may only be performed on a vehicle that is allowed. A
  ///     vehicle is allowed if
  ///     [Shipment.allowed_vehicle_indices][google.cloud.optimization.v1.Shipment.allowed_vehicle_indices]
  ///     is empty or its `vehicle_index` is included in
  ///     [Shipment.allowed_vehicle_indices][google.cloud.optimization.v1.Shipment.allowed_vehicle_indices].
  ///
  /// If the injected solution is not feasible, a validation error is not
  /// necessarily returned and an error indicating infeasibility may be returned
  /// instead.
  ///
  /// [google.cloud.optimization.v1.Shipment.allowed_vehicle_indices]: <doc:Shipment/allowedVehicleIndices>
  public var injectedFirstSolutionRoutes: [ShipmentRoute] = []

  /// Constrain the optimization algorithm to find a final solution that is
  /// similar to a previous solution. For example, this may be used to freeze
  /// portions of routes which have already been completed or which are to be
  /// completed but must not be modified.
  ///
  /// If the injected solution is not feasible, a validation error is not
  /// necessarily returned and an error indicating infeasibility may be returned
  /// instead.
  public var injectedSolutionConstraint: InjectedSolutionConstraint? = nil

  /// If non-empty, the given routes will be refreshed, without modifying their
  /// underlying sequence of visits or travel times: only other details will be
  /// updated. This does not solve the model.
  ///
  /// As of 2020/11, this only populates the polylines of non-empty routes and
  /// requires that `populate_polylines` is true.
  ///
  /// The `route_polyline` fields of the passed-in routes may be inconsistent
  /// with route `transitions`.
  ///
  /// This field must not be used together with `injected_first_solution_routes`
  /// or `injected_solution_constraint`.
  ///
  /// `Shipment.ignore` and `Vehicle.ignore` have no effect on the behavior.
  /// Polylines are still populated between all visits in all non-empty routes
  /// regardless of whether the related shipments or vehicles are ignored.
  public var refreshDetailsRoutes: [ShipmentRoute] = []

  /// If true:
  ///
  ///   * uses
  ///   [ShipmentRoute.vehicle_label][google.cloud.optimization.v1.ShipmentRoute.vehicle_label]
  ///   instead of `vehicle_index` to
  ///     match routes in an injected solution with vehicles in the request;
  ///     reuses the mapping of original
  ///     [ShipmentRoute.vehicle_index][google.cloud.optimization.v1.ShipmentRoute.vehicle_index]
  ///     to new
  ///     [ShipmentRoute.vehicle_index][google.cloud.optimization.v1.ShipmentRoute.vehicle_index]
  ///     to update
  ///     [ConstraintRelaxation.vehicle_indices][google.cloud.optimization.v1.InjectedSolutionConstraint.ConstraintRelaxation.vehicle_indices]
  ///     if non-empty, but the mapping must be unambiguous (i.e., multiple
  ///     `ShipmentRoute`s must not share the same original `vehicle_index`).
  ///   * uses
  ///   [ShipmentRoute.Visit.shipment_label][google.cloud.optimization.v1.ShipmentRoute.Visit.shipment_label]
  ///   instead of `shipment_index`
  ///     to match visits in an injected solution with shipments in the request;
  ///   * uses
  ///   [SkippedShipment.label][google.cloud.optimization.v1.SkippedShipment.label]
  ///   instead of
  ///   [SkippedShipment.index][google.cloud.optimization.v1.SkippedShipment.index]
  ///   to
  ///     match skipped shipments in the injected solution with request
  ///     shipments.
  ///
  /// This interpretation applies to the `injected_first_solution_routes`,
  /// `injected_solution_constraint`, and `refresh_details_routes` fields.
  /// It can be used when shipment or vehicle indices in the request have
  /// changed since the solution was created, perhaps because shipments or
  /// vehicles have been removed from or added to the request.
  ///
  /// If true, labels in the following categories must appear at most once in
  /// their category:
  ///
  ///   * [Vehicle.label][google.cloud.optimization.v1.Vehicle.label] in the
  ///   request;
  ///   * [Shipment.label][google.cloud.optimization.v1.Shipment.label] in the
  ///   request;
  ///   * [ShipmentRoute.vehicle_label][google.cloud.optimization.v1.ShipmentRoute.vehicle_label] in the injected solution;
  ///   * [SkippedShipment.label][google.cloud.optimization.v1.SkippedShipment.label] and [ShipmentRoute.Visit.shipment_label][google.cloud.optimization.v1.ShipmentRoute.Visit.shipment_label] in
  ///     the injected solution (except pickup/delivery visit pairs, whose
  ///     `shipment_label` must appear twice).
  ///
  /// If a `vehicle_label` in the injected solution does not correspond to a
  /// request vehicle, the corresponding route is removed from the solution
  /// along with its visits. If a `shipment_label` in the injected solution does
  /// not correspond to a request shipment, the corresponding visit is removed
  /// from the solution. If a
  /// [SkippedShipment.label][google.cloud.optimization.v1.SkippedShipment.label]
  /// in the injected solution does not correspond to a request shipment, the
  /// `SkippedShipment` is removed from the solution.
  ///
  /// Removing route visits or entire routes from an injected solution may
  /// have an effect on the implied constraints, which may lead to change in
  /// solution, validation errors, or infeasibility.
  ///
  /// NOTE: The caller must ensure that each
  /// [Vehicle.label][google.cloud.optimization.v1.Vehicle.label] (resp.
  /// [Shipment.label][google.cloud.optimization.v1.Shipment.label]) uniquely
  /// identifies a vehicle (resp. shipment) entity used across the two relevant
  /// requests: the past request that produced the `OptimizeToursResponse` used
  /// in the injected solution and the current request that includes the injected
  /// solution. The uniqueness checks described above are not enough to guarantee
  /// this requirement.
  ///
  /// [google.cloud.optimization.v1.InjectedSolutionConstraint.ConstraintRelaxation.vehicle_indices]: <doc:InjectedSolutionConstraint/ConstraintRelaxation/vehicleIndices>
  /// [google.cloud.optimization.v1.Shipment.label]: <doc:Shipment/label>
  /// [google.cloud.optimization.v1.ShipmentRoute.Visit.shipment_label]: <doc:ShipmentRoute/Visit/shipmentLabel>
  /// [google.cloud.optimization.v1.ShipmentRoute.vehicle_index]: <doc:ShipmentRoute/vehicleIndex>
  /// [google.cloud.optimization.v1.ShipmentRoute.vehicle_label]: <doc:ShipmentRoute/vehicleLabel>
  /// [google.cloud.optimization.v1.SkippedShipment.index]: <doc:SkippedShipment/index>
  /// [google.cloud.optimization.v1.SkippedShipment.label]: <doc:SkippedShipment/label>
  /// [google.cloud.optimization.v1.Vehicle.label]: <doc:Vehicle/label>
  public var interpretInjectedSolutionsUsingLabels: Swift.Bool = Swift.Bool()

  /// Consider traffic estimation in calculating `ShipmentRoute` fields
  /// [Transition.travel_duration][google.cloud.optimization.v1.ShipmentRoute.Transition.travel_duration],
  /// [Visit.start_time][google.cloud.optimization.v1.ShipmentRoute.Visit.start_time],
  /// and `vehicle_end_time`; in setting the
  /// [ShipmentRoute.has_traffic_infeasibilities][google.cloud.optimization.v1.ShipmentRoute.has_traffic_infeasibilities]
  /// field, and in calculating the
  /// [OptimizeToursResponse.total_cost][google.cloud.optimization.v1.OptimizeToursResponse.total_cost]
  /// field.
  ///
  /// [google.cloud.optimization.v1.OptimizeToursResponse.total_cost]: <doc:OptimizeToursResponse/totalCost>
  /// [google.cloud.optimization.v1.ShipmentRoute.Transition.travel_duration]: <doc:ShipmentRoute/Transition/travelDuration>
  /// [google.cloud.optimization.v1.ShipmentRoute.Visit.start_time]: <doc:ShipmentRoute/Visit/startTime>
  /// [google.cloud.optimization.v1.ShipmentRoute.has_traffic_infeasibilities]: <doc:ShipmentRoute/hasTrafficInfeasibilities>
  public var considerRoadTraffic: Swift.Bool = Swift.Bool()

  /// If true, polylines will be populated in response `ShipmentRoute`s.
  public var populatePolylines: Swift.Bool = Swift.Bool()

  /// If true, polylines will be populated in response
  /// [ShipmentRoute.transitions][google.cloud.optimization.v1.ShipmentRoute.transitions].
  /// Note that in this case, the polylines will also be populated in the
  /// deprecated `travel_steps`.
  ///
  /// [google.cloud.optimization.v1.ShipmentRoute.transitions]: <doc:ShipmentRoute/transitions>
  public var populateTransitionPolylines: Swift.Bool = Swift.Bool()

  /// If this is set, then the request can have a deadline
  /// (see https://grpc.io/blog/deadlines) of up to 60 minutes.
  /// Otherwise, the maximum deadline is only 30 minutes.
  /// Note that long-lived requests have a significantly larger (but still small)
  /// risk of interruption.
  public var allowLargeDeadlineDespiteInterruptionRisk: Swift.Bool = Swift.Bool()

  /// If true, travel distances will be computed using geodesic distances instead
  /// of Google Maps distances, and travel times will be computed using geodesic
  /// distances with a speed defined by `geodesic_meters_per_second`.
  public var useGeodesicDistances: Swift.Bool = Swift.Bool()

  /// When `use_geodesic_distances` is true, this field must be set and defines
  /// the speed applied to compute travel times. Its value must be at least 1.0
  /// meters/seconds.
  public var geodesicMetersPerSecond: Swift.Double? = nil

  /// Truncates the number of validation errors returned. These errors are
  /// typically attached to an INVALID_ARGUMENT error payload as a BadRequest
  /// error detail (https://cloud.google.com/apis/design/errors#error_details),
  /// unless solving_mode=VALIDATE_ONLY: see the
  /// [OptimizeToursResponse.validation_errors][google.cloud.optimization.v1.OptimizeToursResponse.validation_errors]
  /// field.
  /// This defaults to 100 and is capped at 10,000.
  ///
  /// [google.cloud.optimization.v1.OptimizeToursResponse.validation_errors]: <doc:OptimizeToursResponse/validationErrors>
  public var maxValidationErrors: Swift.Int32? = nil

  /// Label that may be used to identify this request, reported back in the
  /// [OptimizeToursResponse.request_label][google.cloud.optimization.v1.OptimizeToursResponse.request_label].
  ///
  /// [google.cloud.optimization.v1.OptimizeToursResponse.request_label]: <doc:OptimizeToursResponse/requestLabel>
  public var label: Swift.String = Swift.String()

  /// Deprecated: Use
  /// [OptimizeToursRequest.populate_transition_polylines][google.cloud.optimization.v1.OptimizeToursRequest.populate_transition_polylines]
  /// instead. If true, polylines will be populated in response
  /// [ShipmentRoute.transitions][google.cloud.optimization.v1.ShipmentRoute.transitions].
  /// Note that in this case, the polylines will also be populated in the
  /// deprecated `travel_steps`.
  ///
  /// [google.cloud.optimization.v1.OptimizeToursRequest.populate_transition_polylines]: <doc:OptimizeToursRequest/populateTransitionPolylines>
  /// [google.cloud.optimization.v1.ShipmentRoute.transitions]: <doc:ShipmentRoute/transitions>
  @available(*, deprecated)
  public var populateTravelStepPolylines: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `OptimizeToursRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OptimizeToursRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Defines how the solver should handle the request. In all modes but
  /// `VALIDATE_ONLY`, if the request is invalid, you will receive an
  /// `INVALID_REQUEST` error. See
  /// [max_validation_errors][google.cloud.optimization.v1.OptimizeToursRequest.max_validation_errors]
  /// to cap the number of errors returned.
  ///
  /// [google.cloud.optimization.v1.OptimizeToursRequest.max_validation_errors]: <doc:OptimizeToursRequest/maxValidationErrors>
  public enum SolvingMode: Codable, Equatable, Sendable {
    /// Solve the model.
    case defaultSolve
    /// Only validates the model without solving it: populates as many
    /// [OptimizeToursResponse.validation_errors][google.cloud.optimization.v1.OptimizeToursResponse.validation_errors]
    /// as possible.
    ///
    /// [google.cloud.optimization.v1.OptimizeToursResponse.validation_errors]: <doc:OptimizeToursResponse/validationErrors>
    case validateOnly
    /// Only populates
    /// [OptimizeToursResponse.validation_errors][google.cloud.optimization.v1.OptimizeToursResponse.validation_errors]
    /// or
    /// [OptimizeToursResponse.skipped_shipments][google.cloud.optimization.v1.OptimizeToursResponse.skipped_shipments],
    /// and doesn't actually solve the rest of the request (`status` and `routes`
    /// are unset in the response).
    /// If infeasibilities in `injected_solution_constraint` routes are detected
    /// they are populated in the
    /// [OptimizeToursResponse.validation_errors][google.cloud.optimization.v1.OptimizeToursResponse.validation_errors]
    /// field and
    /// [OptimizeToursResponse.skipped_shipments][google.cloud.optimization.v1.OptimizeToursResponse.skipped_shipments]
    /// is left empty.
    ///
    /// *IMPORTANT*: not all infeasible shipments are returned here, but only the
    /// ones that are detected as infeasible during preprocessing.
    ///
    /// [google.cloud.optimization.v1.OptimizeToursResponse.skipped_shipments]: <doc:OptimizeToursResponse/skippedShipments>
    /// [google.cloud.optimization.v1.OptimizeToursResponse.validation_errors]: <doc:OptimizeToursResponse/validationErrors>
    case detectSomeInfeasibleShipments
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .defaultSolve
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .defaultSolve: return 0
      case .validateOnly: return 1
      case .detectSomeInfeasibleShipments: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .defaultSolve: return "DEFAULT_SOLVE"
      case .validateOnly: return "VALIDATE_ONLY"
      case .detectSomeInfeasibleShipments: return "DETECT_SOME_INFEASIBLE_SHIPMENTS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SolvingMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DEFAULT_SOLVE": self = .defaultSolve
      case "VALIDATE_ONLY": self = .validateOnly
      case "DETECT_SOME_INFEASIBLE_SHIPMENTS": self = .detectSomeInfeasibleShipments
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SolvingMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .defaultSolve
      case 1: self = .validateOnly
      case 2: self = .detectSomeInfeasibleShipments
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .defaultSolve: return try container.encode(0)
      case .validateOnly: return try container.encode(1)
      case .detectSomeInfeasibleShipments: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Mode defining the behavior of the search, trading off latency versus
  /// solution quality. In all modes, the global request deadline is enforced.
  public enum SearchMode: Codable, Equatable, Sendable {
    /// Unspecified search mode, equivalent to `RETURN_FAST`.
    case unspecified
    /// Stop the search after finding the first good solution.
    case returnFast
    /// Spend all the available time to search for better solutions.
    case consumeAllAvailableTime
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .returnFast: return 1
      case .consumeAllAvailableTime: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SEARCH_MODE_UNSPECIFIED"
      case .returnFast: return "RETURN_FAST"
      case .consumeAllAvailableTime: return "CONSUME_ALL_AVAILABLE_TIME"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SearchMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SEARCH_MODE_UNSPECIFIED": self = .unspecified
      case "RETURN_FAST": self = .returnFast
      case "CONSUME_ALL_AVAILABLE_TIME": self = .consumeAllAvailableTime
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SearchMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .returnFast
      case 2: self = .consumeAllAvailableTime
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .returnFast: return try container.encode(1)
      case .consumeAllAvailableTime: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.OptimizeToursRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
