// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Response after solving a tour optimization problem containing the routes
/// followed by each vehicle, the shipments which have been skipped and the
/// overall cost of the solution.
public struct OptimizeToursResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Routes computed for each vehicle; the i-th route corresponds to the i-th
  /// vehicle in the model.
  public var routes: [ShipmentRoute] = []

  /// Copy of the
  /// [OptimizeToursRequest.label][google.cloud.optimization.v1.OptimizeToursRequest.label],
  /// if a label was specified in the request.
  ///
  /// [google.cloud.optimization.v1.OptimizeToursRequest.label]: <doc:OptimizeToursRequest/label>
  public var requestLabel: Swift.String = Swift.String()

  /// The list of all shipments skipped.
  public var skippedShipments: [SkippedShipment] = []

  /// List of all the validation errors that we were able to detect
  /// independently. See the "MULTIPLE ERRORS" explanation for the
  /// [OptimizeToursValidationError][google.cloud.optimization.v1.OptimizeToursValidationError]
  /// message.
  ///
  /// [google.cloud.optimization.v1.OptimizeToursValidationError]: <doc:OptimizeToursValidationError>
  public var validationErrors: [OptimizeToursValidationError] = []

  /// Duration, distance and usage metrics for this solution.
  public var metrics: OptimizeToursResponse.Metrics? = nil

  /// Deprecated: Use
  /// [Metrics.total_cost][google.cloud.optimization.v1.OptimizeToursResponse.Metrics.total_cost]
  /// instead. Total cost of the solution. This takes into account all costs:
  /// costs per per hour and travel hour, fixed vehicle costs, unperformed
  /// shipment penalty costs, global duration cost, etc.
  ///
  /// [google.cloud.optimization.v1.OptimizeToursResponse.Metrics.total_cost]: <doc:OptimizeToursResponse/Metrics/totalCost>
  @available(*, deprecated)
  public var totalCost: Swift.Double = Swift.Double()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OptimizeToursResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OptimizeToursResponse().with { $0.routes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let routes = CodingKeys(stringValue: "routes")
    static let requestLabel = CodingKeys(stringValue: "requestLabel")
    static let skippedShipments = CodingKeys(stringValue: "skippedShipments")
    static let validationErrors = CodingKeys(stringValue: "validationErrors")
    static let metrics = CodingKeys(stringValue: "metrics")
    static let totalCost = CodingKeys(stringValue: "totalCost")

    static let _knownKeys: Set<Swift.String> = [
      "routes",
      "requestLabel",
      "skippedShipments",
      "validationErrors",
      "metrics",
      "totalCost",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([ShipmentRoute].self, forKey: .routes) {
      self.routes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestLabel) {
      self.requestLabel = value
    }
    if let value = try container.decodeIfPresent([SkippedShipment].self, forKey: .skippedShipments)
    {
      self.skippedShipments = value
    }
    if let value = try container.decodeIfPresent(
      [OptimizeToursValidationError].self, forKey: .validationErrors)
    {
      self.validationErrors = value
    }
    self.metrics = try container.decodeIfPresent(
      OptimizeToursResponse.Metrics.self, forKey: .metrics)
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .totalCost) {
      self.totalCost = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.routes, forKey: .routes)
    try container.encode(self.requestLabel, forKey: .requestLabel)
    try container.encode(self.skippedShipments, forKey: .skippedShipments)
    try container.encode(self.validationErrors, forKey: .validationErrors)
    try container.encodeIfPresent(self.metrics, forKey: .metrics)
    try container.encode(self.totalCost, forKey: .totalCost)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Overall metrics, aggregated over all routes.
  public struct Metrics: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Aggregated over the routes. Each metric is the sum (or max, for loads)
    /// over all
    /// [ShipmentRoute.metrics][google.cloud.optimization.v1.ShipmentRoute.metrics]
    /// fields of the same name.
    ///
    /// [google.cloud.optimization.v1.ShipmentRoute.metrics]: <doc:ShipmentRoute/metrics>
    public var aggregatedRouteMetrics: AggregatedMetrics? = nil

    /// Number of mandatory shipments skipped.
    public var skippedMandatoryShipmentCount: Swift.Int32 = Swift.Int32()

    /// Number of vehicles used. Note: if a vehicle route is empty and
    /// [Vehicle.used_if_route_is_empty][google.cloud.optimization.v1.Vehicle.used_if_route_is_empty]
    /// is true, the vehicle is considered used.
    ///
    /// [google.cloud.optimization.v1.Vehicle.used_if_route_is_empty]: <doc:Vehicle/usedIfRouteIsEmpty>
    public var usedVehicleCount: Swift.Int32 = Swift.Int32()

    /// The earliest start time for a used vehicle, computed as the minimum over
    /// all used vehicles of
    /// [ShipmentRoute.vehicle_start_time][google.cloud.optimization.v1.ShipmentRoute.vehicle_start_time].
    ///
    /// [google.cloud.optimization.v1.ShipmentRoute.vehicle_start_time]: <doc:ShipmentRoute/vehicleStartTime>
    public var earliestVehicleStartTime: GoogleWKT.Timestamp? = nil

    /// The latest end time for a used vehicle, computed as the maximum over all
    /// used vehicles of
    /// [ShipmentRoute.vehicle_end_time][google.cloud.optimization.v1.ShipmentRoute.vehicle_end_time].
    ///
    /// [google.cloud.optimization.v1.ShipmentRoute.vehicle_end_time]: <doc:ShipmentRoute/vehicleEndTime>
    public var latestVehicleEndTime: GoogleWKT.Timestamp? = nil

    /// Cost of the solution, broken down by cost-related request fields.
    /// The keys are proto paths, relative to the input OptimizeToursRequest,
    /// e.g. "model.shipments.pickups.cost", and the values are the total cost
    /// generated by the corresponding cost field, aggregated over the whole
    /// solution. In other words, costs["model.shipments.pickups.cost"] is the
    /// sum of all pickup costs over the solution. All costs defined in the model
    /// are reported in detail here with the exception of costs related to
    /// TransitionAttributes that are only reported in an aggregated way as of
    /// 2022/01.
    public var costs: [Swift.String: Swift.Double] = [:]

    /// Total cost of the solution. The sum of all values in the costs map.
    public var totalCost: Swift.Double = Swift.Double()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Metrics`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Metrics().with { $0.aggregatedRouteMetrics = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let aggregatedRouteMetrics = CodingKeys(stringValue: "aggregatedRouteMetrics")
      static let skippedMandatoryShipmentCount = CodingKeys(
        stringValue: "skippedMandatoryShipmentCount")
      static let usedVehicleCount = CodingKeys(stringValue: "usedVehicleCount")
      static let earliestVehicleStartTime = CodingKeys(stringValue: "earliestVehicleStartTime")
      static let latestVehicleEndTime = CodingKeys(stringValue: "latestVehicleEndTime")
      static let costs = CodingKeys(stringValue: "costs")
      static let totalCost = CodingKeys(stringValue: "totalCost")

      static let _knownKeys: Set<Swift.String> = [
        "aggregatedRouteMetrics",
        "skippedMandatoryShipmentCount",
        "usedVehicleCount",
        "earliestVehicleStartTime",
        "latestVehicleEndTime",
        "costs",
        "totalCost",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.aggregatedRouteMetrics = try container.decodeIfPresent(
        AggregatedMetrics.self, forKey: .aggregatedRouteMetrics)
      if let value = try container.decodeIfPresent(
        Swift.Int32.self, forKey: .skippedMandatoryShipmentCount)
      {
        self.skippedMandatoryShipmentCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .usedVehicleCount) {
        self.usedVehicleCount = value
      }
      self.earliestVehicleStartTime = try container.decodeIfPresent(
        GoogleWKT.Timestamp.self, forKey: .earliestVehicleStartTime)
      self.latestVehicleEndTime = try container.decodeIfPresent(
        GoogleWKT.Timestamp.self, forKey: .latestVehicleEndTime)
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.Double].self, forKey: .costs)
      {
        self.costs = value
      }
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .totalCost) {
        self.totalCost = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.aggregatedRouteMetrics, forKey: .aggregatedRouteMetrics)
      try container.encode(
        self.skippedMandatoryShipmentCount, forKey: .skippedMandatoryShipmentCount)
      try container.encode(self.usedVehicleCount, forKey: .usedVehicleCount)
      try container.encodeIfPresent(
        self.earliestVehicleStartTime, forKey: .earliestVehicleStartTime)
      try container.encodeIfPresent(self.latestVehicleEndTime, forKey: .latestVehicleEndTime)
      try container.encode(self.costs, forKey: .costs)
      try container.encode(self.totalCost, forKey: .totalCost)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.OptimizeToursResponse.Metrics"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.OptimizeToursResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
