// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The desired output location.
public struct OutputConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The output data format that used to store the results in Cloud Storage.
  public var dataFormat: DataFormat = DataFormat()

  /// The location of the output result in cloud storage.
  /// Required.
  public var destination: OneOf_Destination? = nil

  /// Initialize a new instance of `OutputConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OutputConfig().with { $0.gcsDestination = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gcsDestination = "gcsDestination"
    case dataFormat = "dataFormat"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.dataFormat = try container.decode(DataFormat.self, forKey: .dataFormat)

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let gcsDestination = try container.decodeIfPresent(
      GcsDestination?.self, forKey: .gcsDestination)
    {
      try destinationCheckAndSet(.gcsDestination(gcsDestination))
    }
    self.destination = destination
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.dataFormat, forKey: .dataFormat)

    if let choice = self.destination {
      switch choice {
      case .gcsDestination(let value):
        try container.encode(value, forKey: .gcsDestination)
      }
    }
  }

  /// The location of the output result in cloud storage.
  /// Required.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// The Google Cloud Storage location to write the output to.
    indirect case gcsDestination(GcsDestination?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.OutputConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
