// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Encapsulates a set of optional conditions to satisfy when calculating
/// vehicle routes. This is similar to `RouteModifiers` in the Google Maps
/// Platform API; see:
/// https://developers.google.com/maps/documentation/routes/reference/rest/v2/RouteModifiers.
public struct RouteModifiers: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Specifies whether to avoid toll roads where reasonable. Preference will be
  /// given to routes not containing toll roads. Applies only to motorized travel
  /// modes.
  public var avoidTolls: Swift.Bool = Swift.Bool()

  /// Specifies whether to avoid highways where reasonable. Preference will be
  /// given to routes not containing highways. Applies only to motorized travel
  /// modes.
  public var avoidHighways: Swift.Bool = Swift.Bool()

  /// Specifies whether to avoid ferries where reasonable. Preference will be
  /// given to routes not containing travel by ferries. Applies only to motorized
  /// travel modes.
  public var avoidFerries: Swift.Bool = Swift.Bool()

  /// Optional. Specifies whether to avoid navigating indoors where reasonable.
  /// Preference will be given to routes not containing indoor navigation.
  /// Applies only to the `WALKING` travel mode.
  public var avoidIndoor: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `RouteModifiers`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RouteModifiers().with { $0.avoidTolls = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let avoidTolls = CodingKeys(stringValue: "avoidTolls")
    static let avoidHighways = CodingKeys(stringValue: "avoidHighways")
    static let avoidFerries = CodingKeys(stringValue: "avoidFerries")
    static let avoidIndoor = CodingKeys(stringValue: "avoidIndoor")

    static let _knownKeys: Set<Swift.String> = [
      "avoidTolls",
      "avoidHighways",
      "avoidFerries",
      "avoidIndoor",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .avoidTolls) {
      self.avoidTolls = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .avoidHighways) {
      self.avoidHighways = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .avoidFerries) {
      self.avoidFerries = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .avoidIndoor) {
      self.avoidIndoor = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.avoidTolls, forKey: .avoidTolls)
    try container.encode(self.avoidHighways, forKey: .avoidHighways)
    try container.encode(self.avoidFerries, forKey: .avoidFerries)
    try container.encode(self.avoidIndoor, forKey: .avoidIndoor)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.RouteModifiers"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
