// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Encapsulates a set of optional conditions to satisfy when calculating
/// vehicle routes. This is similar to `RouteModifiers` in the Google Maps
/// Platform API; see:
/// https://developers.google.com/maps/documentation/routes/reference/rest/v2/RouteModifiers.
public struct RouteModifiers: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Specifies whether to avoid toll roads where reasonable. Preference will be
  /// given to routes not containing toll roads. Applies only to motorized travel
  /// modes.
  public var avoidTolls: Swift.Bool = Swift.Bool()

  /// Specifies whether to avoid highways where reasonable. Preference will be
  /// given to routes not containing highways. Applies only to motorized travel
  /// modes.
  public var avoidHighways: Swift.Bool = Swift.Bool()

  /// Specifies whether to avoid ferries where reasonable. Preference will be
  /// given to routes not containing travel by ferries. Applies only to motorized
  /// travel modes.
  public var avoidFerries: Swift.Bool = Swift.Bool()

  /// Optional. Specifies whether to avoid navigating indoors where reasonable.
  /// Preference will be given to routes not containing indoor navigation.
  /// Applies only to the `WALKING` travel mode.
  public var avoidIndoor: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `RouteModifiers`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RouteModifiers().with { $0.avoidTolls = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.RouteModifiers"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
