// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A vehicle's route can be decomposed, along the time axis, like this (we
/// assume there are n visits):
/// ```
///   |            |            |          |       |  T[2], |        |      |
///   | Transition |  Visit #0  |          |       |  V[2], |        |      |
///   |     #0     |    aka     |   T[1]   |  V[1] |  ...   | V[n-1] | T[n] |
///   |  aka T[0]  |    V[0]    |          |       | V[n-2],|        |      |
///   |            |            |          |       | T[n-1] |        |      |
///   ^            ^            ^          ^       ^        ^        ^      ^
/// vehicle    V[0].start   V[0].end     V[1].   V[1].    V[n].    V[n]. vehicle
///  start     (arrival)   (departure)   start   end      start    end     end
/// ```
/// Note that we make a difference between:
///
/// * "punctual events", such as the vehicle start and end and each visit's start
///   and end (aka arrival and departure). They happen at a given second.
/// * "time intervals", such as the visits themselves, and the transition between
///   visits. Though time intervals can sometimes have zero duration, i.e. start
///   and end at the same second, they often have a positive duration.
///
/// Invariants:
///
/// * If there are n visits, there are n+1 transitions.
/// * A visit is always surrounded by a transition before it (same index) and a
///   transition after it (index + 1).
/// * The vehicle start is always followed by transition #0.
/// * The vehicle end is always preceded by transition #n.
///
/// Zooming in, here is what happens during a `Transition` and a `Visit`:
/// ```
/// ---+-------------------------------------+-----------------------------+-->
///    |           TRANSITION[i]             |           VISIT[i]          |
///    |                                     |                             |
///    |  * TRAVEL: the vehicle moves from   |      PERFORM the visit:     |
///    |    VISIT[i-1].departure_location to |                             |
///    |    VISIT[i].arrival_location, which |  * Spend some time:         |
///    |    takes a given travel duration    |    the "visit duration".    |
///    |    and distance                     |                             |
///    |                                     |  * Load or unload           |
///    |  * BREAKS: the driver may have      |    some quantities from the |
///    |    breaks (e.g. lunch break).       |    vehicle: the "demand".   |
///    |                                     |                             |
///    |  * WAIT: the driver/vehicle does    |                             |
///    |    nothing. This can happen for     |                             |
///    |    many reasons, for example when   |                             |
///    |    the vehicle reaches the next     |                             |
///    |    event's destination before the   |                             |
///    |    start of its time window         |                             |
///    |                                     |                             |
///    |  * DELAY: *right before* the next   |                             |
///    |    arrival. E.g. the vehicle and/or |                             |
///    |    driver spends time unloading.    |                             |
///    |                                     |                             |
/// ---+-------------------------------------+-----------------------------+-->
///    ^                                     ^                             ^
/// V[i-1].end                           V[i].start                    V[i].end
/// ```
/// Lastly, here is how the TRAVEL, BREAKS, DELAY and WAIT can be arranged
/// during a transition.
///
/// * They don't overlap.
/// * The DELAY is unique and *must* be a contiguous period of time right
///   before the next visit (or vehicle end). Thus, it suffice to know the
///   delay duration to know its start and end time.
/// * The BREAKS are contiguous, non-overlapping periods of time. The
///   response specifies the start time and duration of each break.
/// * TRAVEL and WAIT are "preemptable": they can be interrupted several times
///   during this transition. Clients can assume that travel happens "as soon as
///   possible" and that "wait" fills the remaining time.
///
/// A (complex) example:
/// ```
///                                TRANSITION[i]
/// --++-----+-----------------------------------------------------------++-->
///   ||     |       |           |       |           |         |         ||
///   ||  T  |   B   |     T     |       |     B     |         |    D    ||
///   ||  r  |   r   |     r     |   W   |     r     |    W    |    e    ||
///   ||  a  |   e   |     a     |   a   |     e     |    a    |    l    ||
///   ||  v  |   a   |     v     |   i   |     a     |    i    |    a    ||
///   ||  e  |   k   |     e     |   t   |     k     |    t    |    y    ||
///   ||  l  |       |     l     |       |           |         |         ||
///   ||     |       |           |       |           |         |         ||
/// --++-----------------------------------------------------------------++-->
/// ```
public struct ShipmentRoute: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Vehicle performing the route, identified by its index in the source
  /// `ShipmentModel`.
  public var vehicleIndex: Swift.Int32 = Swift.Int32()

  /// Label of the vehicle performing this route, equal to
  /// `ShipmentModel.vehicles(vehicle_index).label`, if specified.
  public var vehicleLabel: Swift.String = Swift.String()

  /// Time at which the vehicle starts its route.
  public var vehicleStartTime: GoogleCloudWkt.Timestamp? = nil

  /// Time at which the vehicle finishes its route.
  public var vehicleEndTime: GoogleCloudWkt.Timestamp? = nil

  /// Ordered sequence of visits representing a route.
  /// visits[i] is the i-th visit in the route.
  /// If this field is empty, the vehicle is considered as unused.
  public var visits: [ShipmentRoute.Visit] = []

  /// Ordered list of transitions for the route.
  public var transitions: [ShipmentRoute.Transition] = []

  /// When
  /// [OptimizeToursRequest.consider_road_traffic][google.cloud.optimization.v1.OptimizeToursRequest.consider_road_traffic],
  /// is set to true, this field indicates that inconsistencies in route timings
  /// are predicted using traffic-based travel duration estimates. There may be
  /// insufficient time to complete traffic-adjusted travel, delays, and breaks
  /// between visits, before the first visit, or after the last visit, while
  /// still satisfying the visit and vehicle time windows. For example,
  ///
  /// ```
  ///   start_time(previous_visit) + duration(previous_visit) +
  ///   travel_duration(previous_visit, next_visit) > start_time(next_visit)
  /// ```
  ///
  /// Arrival at next_visit will likely happen later than its current
  /// time window due the increased estimate of travel time
  /// `travel_duration(previous_visit, next_visit)` due to traffic. Also, a break
  /// may be forced to overlap with a visit due to an increase in travel time
  /// estimates and visit or break time window restrictions.
  ///
  /// [google.cloud.optimization.v1.OptimizeToursRequest.consider_road_traffic]: <doc:OptimizeToursRequest/considerRoadTraffic>
  public var hasTrafficInfeasibilities: Swift.Bool = Swift.Bool()

  /// The encoded polyline representation of the route.
  /// This field is only populated if
  /// [OptimizeToursRequest.populate_polylines][google.cloud.optimization.v1.OptimizeToursRequest.populate_polylines]
  /// is set to true.
  ///
  /// [google.cloud.optimization.v1.OptimizeToursRequest.populate_polylines]: <doc:OptimizeToursRequest/populatePolylines>
  public var routePolyline: ShipmentRoute.EncodedPolyline? = nil

  /// Breaks scheduled for the vehicle performing this route.
  /// The `breaks` sequence represents time intervals, each starting at the
  /// corresponding `start_time` and lasting `duration` seconds.
  public var breaks: [ShipmentRoute.Break] = []

  /// Duration, distance and load metrics for this route. The fields of
  /// [AggregatedMetrics][google.cloud.optimization.v1.AggregatedMetrics] are
  /// summed over all
  /// [ShipmentRoute.transitions][google.cloud.optimization.v1.ShipmentRoute.transitions]
  /// or
  /// [ShipmentRoute.visits][google.cloud.optimization.v1.ShipmentRoute.visits],
  /// depending on the context.
  ///
  /// [google.cloud.optimization.v1.AggregatedMetrics]: <doc:AggregatedMetrics>
  /// [google.cloud.optimization.v1.ShipmentRoute.transitions]: <doc:ShipmentRoute/transitions>
  /// [google.cloud.optimization.v1.ShipmentRoute.visits]: <doc:ShipmentRoute/visits>
  public var metrics: AggregatedMetrics? = nil

  /// Cost of the route, broken down by cost-related request fields.
  /// The keys are proto paths, relative to the input OptimizeToursRequest, e.g.
  /// "model.shipments.pickups.cost", and the values are the total cost
  /// generated by the corresponding cost field, aggregated over the whole route.
  /// In other words, costs["model.shipments.pickups.cost"] is the sum of all
  /// pickup costs over the route. All costs defined in the model are reported in
  /// detail here with the exception of costs related to TransitionAttributes
  /// that are only reported in an aggregated way as of 2022/01.
  public var routeCosts: [Swift.String: Swift.Double] = [:]

  /// Total cost of the route. The sum of all costs in the cost map.
  public var routeTotalCost: Swift.Double = Swift.Double()

  /// Deprecated: Use
  /// [Transition.vehicle_loads][google.cloud.optimization.v1.ShipmentRoute.Transition.vehicle_loads]
  /// instead. Vehicle loads upon arrival at its end location, for each type
  /// specified in
  /// [Vehicle.capacities][google.cloud.optimization.v1.Vehicle.capacities],
  /// `start_load_intervals`, `end_load_intervals` or demands. Exception: we omit
  /// loads for quantity types unconstrained by intervals and that don't have any
  /// non-zero demand on the route.
  ///
  /// [google.cloud.optimization.v1.ShipmentRoute.Transition.vehicle_loads]: <doc:ShipmentRoute/Transition/vehicleLoads>
  /// [google.cloud.optimization.v1.Vehicle.capacities]: <doc:Vehicle/capacities>
  @available(*, deprecated)
  public var endLoads: [CapacityQuantity] = []

  /// Deprecated: Use
  /// [ShipmentRoute.transitions][google.cloud.optimization.v1.ShipmentRoute.transitions]
  /// instead. Ordered list of travel steps for the route.
  ///
  /// [google.cloud.optimization.v1.ShipmentRoute.transitions]: <doc:ShipmentRoute/transitions>
  @available(*, deprecated)
  public var travelSteps: [ShipmentRoute.TravelStep] = []

  /// Deprecated: No longer used.
  /// This field will only be populated at the
  /// [ShipmentRoute.Visit][google.cloud.optimization.v1.ShipmentRoute.Visit]
  /// level.
  ///
  /// This field is the extra detour time due to the shipments visited on the
  /// route.
  ///
  /// It is equal to `vehicle_end_time` - `vehicle_start_time` - travel duration
  /// from the vehicle's start_location to its `end_location`.
  ///
  /// [google.cloud.optimization.v1.ShipmentRoute.Visit]: <doc:ShipmentRoute/Visit>
  @available(*, deprecated)
  public var vehicleDetour: GoogleCloudWkt.Duration? = nil

  /// Deprecated: Delay occurring before the vehicle end. See
  /// [TransitionAttributes.delay][google.cloud.optimization.v1.TransitionAttributes.delay].
  ///
  /// [google.cloud.optimization.v1.TransitionAttributes.delay]: <doc:TransitionAttributes/delay>
  @available(*, deprecated)
  public var delayBeforeVehicleEnd: ShipmentRoute.Delay? = nil

  /// Initialize a new instance of `ShipmentRoute`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ShipmentRoute().with { $0.vehicleIndex = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Deprecated: Use
  /// [ShipmentRoute.Transition.delay_duration][google.cloud.optimization.v1.ShipmentRoute.Transition.delay_duration]
  /// instead. Time interval spent on the route resulting from a
  /// [TransitionAttributes.delay][google.cloud.optimization.v1.TransitionAttributes.delay].
  ///
  /// [google.cloud.optimization.v1.ShipmentRoute.Transition.delay_duration]: <doc:ShipmentRoute/Transition/delayDuration>
  /// [google.cloud.optimization.v1.TransitionAttributes.delay]: <doc:TransitionAttributes/delay>
  @available(*, deprecated)
  public struct Delay: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Start of the delay.
    public var startTime: GoogleCloudWkt.Timestamp? = nil

    /// Duration of the delay.
    public var duration: GoogleCloudWkt.Duration? = nil

    /// Initialize a new instance of `Delay`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Delay().with { $0.startTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.ShipmentRoute.Delay"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A visit performed during a route. This visit corresponds to a pickup or a
  /// delivery of a `Shipment`.
  public struct Visit: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Index of the `shipments` field in the source
    /// [ShipmentModel][google.cloud.optimization.v1.ShipmentModel].
    ///
    /// [google.cloud.optimization.v1.ShipmentModel]: <doc:ShipmentModel>
    public var shipmentIndex: Swift.Int32 = Swift.Int32()

    /// If true the visit corresponds to a pickup of a `Shipment`. Otherwise, it
    /// corresponds to a delivery.
    public var isPickup: Swift.Bool = Swift.Bool()

    /// Index of `VisitRequest` in either the pickup or delivery field of the
    /// `Shipment` (see `is_pickup`).
    public var visitRequestIndex: Swift.Int32 = Swift.Int32()

    /// Time at which the visit starts. Note that the vehicle may arrive earlier
    /// than this at the visit location. Times are consistent with the
    /// `ShipmentModel`.
    public var startTime: GoogleCloudWkt.Timestamp? = nil

    /// Total visit load demand as the sum of the shipment and the visit request
    /// `load_demands`. The values are negative if the visit is a delivery.
    /// Demands are reported for the same types as the
    /// [Transition.loads][google.cloud.optimization.v1.ShipmentRoute.Transition]
    /// (see this field).
    ///
    /// [google.cloud.optimization.v1.ShipmentRoute.Transition]: <doc:ShipmentRoute/Transition>
    public var loadDemands: [Swift.String: Shipment.Load] = [:]

    /// Extra detour time due to the shipments visited on the route before the
    /// visit and to the potential waiting time induced by time windows.
    /// If the visit is a delivery, the detour is computed from the corresponding
    /// pickup visit and is equal to:
    /// ```
    /// start_time(delivery) - start_time(pickup)
    /// - (duration(pickup) + travel duration from the pickup location
    /// to the delivery location).
    /// ```
    /// Otherwise, it is computed from the vehicle `start_location` and is equal
    /// to:
    /// ```
    /// start_time - vehicle_start_time - travel duration from
    /// the vehicle's `start_location` to the visit.
    /// ```
    public var detour: GoogleCloudWkt.Duration? = nil

    /// Copy of the corresponding `Shipment.label`, if specified in the
    /// `Shipment`.
    public var shipmentLabel: Swift.String = Swift.String()

    /// Copy of the corresponding
    /// [VisitRequest.label][google.cloud.optimization.v1.Shipment.VisitRequest.label],
    /// if specified in the `VisitRequest`.
    ///
    /// [google.cloud.optimization.v1.Shipment.VisitRequest.label]: <doc:Shipment/VisitRequest/label>
    public var visitLabel: Swift.String = Swift.String()

    /// Deprecated: Use
    /// [Transition.vehicle_loads][google.cloud.optimization.v1.ShipmentRoute.Transition.vehicle_loads]
    /// instead. Vehicle loads upon arrival at the visit location, for each type
    /// specified in
    /// [Vehicle.capacities][google.cloud.optimization.v1.Vehicle.capacities],
    /// `start_load_intervals`, `end_load_intervals` or `demands`.
    ///
    /// Exception: we omit loads for quantity types unconstrained by intervals
    /// and that don't have any non-zero demand on the route.
    ///
    /// [google.cloud.optimization.v1.ShipmentRoute.Transition.vehicle_loads]: <doc:ShipmentRoute/Transition/vehicleLoads>
    /// [google.cloud.optimization.v1.Vehicle.capacities]: <doc:Vehicle/capacities>
    @available(*, deprecated)
    public var arrivalLoads: [CapacityQuantity] = []

    /// Deprecated: Use
    /// [ShipmentRoute.Transition.delay_duration][google.cloud.optimization.v1.ShipmentRoute.Transition.delay_duration]
    /// instead. Delay occurring before the visit starts.
    ///
    /// [google.cloud.optimization.v1.ShipmentRoute.Transition.delay_duration]: <doc:ShipmentRoute/Transition/delayDuration>
    @available(*, deprecated)
    public var delayBeforeStart: ShipmentRoute.Delay? = nil

    /// Deprecated: Use
    /// [Visit.load_demands][google.cloud.optimization.v1.ShipmentRoute.Visit.load_demands]
    /// instead.
    ///
    /// [google.cloud.optimization.v1.ShipmentRoute.Visit.load_demands]: <doc:ShipmentRoute/Visit/loadDemands>
    @available(*, deprecated)
    public var demands: [CapacityQuantity] = []

    /// Initialize a new instance of `Visit`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Visit().with { $0.shipmentIndex = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.ShipmentRoute.Visit"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Transition between two events on the route. See the description of
  /// [ShipmentRoute][google.cloud.optimization.v1.ShipmentRoute].
  ///
  /// If the vehicle does not have a `start_location` and/or `end_location`, the
  /// corresponding travel metrics are 0.
  ///
  /// [google.cloud.optimization.v1.ShipmentRoute]: <doc:ShipmentRoute>
  public struct Transition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Travel duration during this transition.
    public var travelDuration: GoogleCloudWkt.Duration? = nil

    /// Distance traveled during the transition.
    public var travelDistanceMeters: Swift.Double = Swift.Double()

    /// When traffic is requested via
    /// [OptimizeToursRequest.consider_road_traffic]
    /// [google.cloud.optimization.v1.OptimizeToursRequest.consider_road_traffic],
    /// and the traffic info couldn't be retrieved for a `Transition`, this
    /// boolean is set to true. This may be temporary (rare hiccup in the
    /// realtime traffic servers) or permanent (no data for this location).
    public var trafficInfoUnavailable: Swift.Bool = Swift.Bool()

    /// Sum of the delay durations applied to this transition. If any, the delay
    /// starts exactly `delay_duration` seconds before the next event (visit or
    /// vehicle end). See
    /// [TransitionAttributes.delay][google.cloud.optimization.v1.TransitionAttributes.delay].
    ///
    /// [google.cloud.optimization.v1.TransitionAttributes.delay]: <doc:TransitionAttributes/delay>
    public var delayDuration: GoogleCloudWkt.Duration? = nil

    /// Sum of the duration of the breaks occurring during this transition, if
    /// any. Details about each break's start time and duration are stored in
    /// [ShipmentRoute.breaks][google.cloud.optimization.v1.ShipmentRoute.breaks].
    ///
    /// [google.cloud.optimization.v1.ShipmentRoute.breaks]: <doc:ShipmentRoute/breaks>
    public var breakDuration: GoogleCloudWkt.Duration? = nil

    /// Time spent waiting during this transition. Wait duration corresponds to
    /// idle time and does not include break time. Also note that this wait time
    /// may be split into several non-contiguous intervals.
    public var waitDuration: GoogleCloudWkt.Duration? = nil

    /// Total duration of the transition, provided for convenience. It is equal
    /// to:
    ///
    /// * next visit `start_time` (or `vehicle_end_time` if this is the last
    /// transition) - this transition's `start_time`;
    /// * if `ShipmentRoute.has_traffic_infeasibilities` is false, the following
    /// additionally holds: `total_duration = travel_duration + delay_duration
    /// + break_duration + wait_duration`.
    public var totalDuration: GoogleCloudWkt.Duration? = nil

    /// Start time of this transition.
    public var startTime: GoogleCloudWkt.Timestamp? = nil

    /// The encoded polyline representation of the route followed during the
    /// transition.
    /// This field is only populated if [populate_transition_polylines]
    /// [google.cloud.optimization.v1.OptimizeToursRequest.populate_transition_polylines]
    /// is set to true.
    public var routePolyline: ShipmentRoute.EncodedPolyline? = nil

    /// Vehicle loads during this transition, for each type that either appears
    /// in this vehicle's
    /// [Vehicle.load_limits][google.cloud.optimization.v1.Vehicle.load_limits],
    /// or that have non-zero
    /// [Shipment.load_demands][google.cloud.optimization.v1.Shipment.load_demands]
    /// on some shipment performed on this route.
    ///
    /// The loads during the first transition are the starting loads of the
    /// vehicle route. Then, after each visit, the visit's `load_demands` are
    /// either added or subtracted to get the next transition's loads, depending
    /// on whether the visit was a pickup or a delivery.
    ///
    /// [google.cloud.optimization.v1.Shipment.load_demands]: <doc:Shipment/loadDemands>
    /// [google.cloud.optimization.v1.Vehicle.load_limits]: <doc:Vehicle/loadLimits>
    public var vehicleLoads: [Swift.String: ShipmentRoute.VehicleLoad] = [:]

    /// Deprecated: Use
    /// [Transition.vehicle_loads][google.cloud.optimization.v1.ShipmentRoute.Transition.vehicle_loads]
    /// instead.
    ///
    /// [google.cloud.optimization.v1.ShipmentRoute.Transition.vehicle_loads]: <doc:ShipmentRoute/Transition/vehicleLoads>
    @available(*, deprecated)
    public var loads: [CapacityQuantity] = []

    /// Initialize a new instance of `Transition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Transition().with { $0.travelDuration = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.ShipmentRoute.Transition"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Reports the actual load of the vehicle at some point along the route,
  /// for a given type (see
  /// [Transition.vehicle_loads][google.cloud.optimization.v1.ShipmentRoute.Transition.vehicle_loads]).
  ///
  /// [google.cloud.optimization.v1.ShipmentRoute.Transition.vehicle_loads]: <doc:ShipmentRoute/Transition/vehicleLoads>
  public struct VehicleLoad: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The amount of load on the vehicle, for the given type. The unit of load
    /// is usually indicated by the type. See
    /// [Transition.vehicle_loads][google.cloud.optimization.v1.ShipmentRoute.Transition.vehicle_loads].
    ///
    /// [google.cloud.optimization.v1.ShipmentRoute.Transition.vehicle_loads]: <doc:ShipmentRoute/Transition/vehicleLoads>
    public var amount: Swift.Int64 = Swift.Int64()

    /// Initialize a new instance of `VehicleLoad`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = VehicleLoad().with { $0.amount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.ShipmentRoute.VehicleLoad"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The encoded representation of a polyline. More information on polyline
  /// encoding can be found here:
  /// https://developers.google.com/maps/documentation/utilities/polylinealgorithm
  /// https://developers.google.com/maps/documentation/javascript/reference/geometry#encoding.
  public struct EncodedPolyline: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// String representing encoded points of the polyline.
    public var points: Swift.String = Swift.String()

    /// Initialize a new instance of `EncodedPolyline`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EncodedPolyline().with { $0.points = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.ShipmentRoute.EncodedPolyline"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Data representing the execution of a break.
  public struct Break: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Start time of a break.
    public var startTime: GoogleCloudWkt.Timestamp? = nil

    /// Duration of a break.
    public var duration: GoogleCloudWkt.Duration? = nil

    /// Initialize a new instance of `Break`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Break().with { $0.startTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.ShipmentRoute.Break"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Deprecated: Use
  /// [ShipmentRoute.Transition][google.cloud.optimization.v1.ShipmentRoute.Transition]
  /// instead. Travel between each visit along the route: from the vehicle's
  /// `start_location` to the first visit's `arrival_location`, then from the
  /// first visit's `departure_location` to the second visit's
  /// `arrival_location`, and so on until the vehicle's `end_location`. This
  /// accounts only for the actual travel between visits, not counting the
  /// waiting time, the time spent performing a visit, nor the distance covered
  /// during a visit.
  ///
  /// Invariant: `travel_steps_size() == visits_size() + 1`.
  ///
  /// If the vehicle does not have a start_ and/or end_location, the
  /// corresponding travel metrics are 0 and/or empty.
  ///
  /// [google.cloud.optimization.v1.ShipmentRoute.Transition]: <doc:ShipmentRoute/Transition>
  @available(*, deprecated)
  public struct TravelStep: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Duration of the travel step.
    public var duration: GoogleCloudWkt.Duration? = nil

    /// Distance traveled during the step.
    public var distanceMeters: Swift.Double = Swift.Double()

    /// When traffic is requested via
    /// [OptimizeToursRequest.consider_road_traffic][google.cloud.optimization.v1.OptimizeToursRequest.consider_road_traffic],
    /// and the traffic info couldn't be retrieved for a TravelStep, this boolean
    /// is set to true. This may be temporary (rare hiccup in the realtime
    /// traffic servers) or permanent (no data for this location).
    ///
    /// [google.cloud.optimization.v1.OptimizeToursRequest.consider_road_traffic]: <doc:OptimizeToursRequest/considerRoadTraffic>
    public var trafficInfoUnavailable: Swift.Bool = Swift.Bool()

    /// The encoded polyline representation of the route followed during the
    /// step.
    ///
    /// This field is only populated if
    /// [OptimizeToursRequest.populate_travel_step_polylines][google.cloud.optimization.v1.OptimizeToursRequest.populate_travel_step_polylines]
    /// is set to true.
    ///
    /// [google.cloud.optimization.v1.OptimizeToursRequest.populate_travel_step_polylines]: <doc:OptimizeToursRequest/populateTravelStepPolylines>
    public var routePolyline: ShipmentRoute.EncodedPolyline? = nil

    /// Initialize a new instance of `TravelStep`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TravelStep().with { $0.duration = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.ShipmentRoute.TravelStep"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.ShipmentRoute"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
