// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Specifies requirements between shipments based on their shipment_type.
/// The specifics of the requirement are defined by the requirement mode.
public struct ShipmentTypeRequirement: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// List of alternative shipment types required by the
  /// `dependent_shipment_types`.
  public var requiredShipmentTypeAlternatives: [Swift.String] = []

  /// All shipments with a type in the `dependent_shipment_types` field require
  /// at least one shipment of type `required_shipment_type_alternatives` to be
  /// visited on the same route.
  ///
  /// NOTE: Chains of requirements such that a `shipment_type` depends on itself
  /// are not allowed.
  public var dependentShipmentTypes: [Swift.String] = []

  /// Mode applied to the requirement.
  public var requirementMode: ShipmentTypeRequirement.RequirementMode =
    ShipmentTypeRequirement.RequirementMode()

  /// Initialize a new instance of `ShipmentTypeRequirement`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ShipmentTypeRequirement().with { $0.requiredShipmentTypeAlternatives = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Modes defining the appearance of dependent shipments on a route.
  public enum RequirementMode: Codable, Equatable, Sendable {
    /// Unspecified requirement mode. This value should never be used.
    case unspecified
    /// In this mode, all "dependent" shipments must share the same vehicle as at
    /// least one of their "required" shipments.
    case performedBySameVehicle
    /// With the `IN_SAME_VEHICLE_AT_PICKUP_TIME` mode, all "dependent"
    /// shipments need to have at least one "required" shipment on their vehicle
    /// at the time of their pickup.
    ///
    /// A "dependent" shipment pickup must therefore have either:
    ///
    /// * A delivery-only "required" shipment delivered on the route after, or
    /// * A "required" shipment picked up on the route before it, and if the
    ///   "required" shipment has a delivery, this delivery must be performed
    ///   after the "dependent" shipment's pickup.
    case inSameVehicleAtPickupTime
    /// Same as before, except the "dependent" shipments need to have a
    /// "required" shipment on their vehicle at the time of their *delivery*.
    case inSameVehicleAtDeliveryTime
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .performedBySameVehicle: return 1
      case .inSameVehicleAtPickupTime: return 2
      case .inSameVehicleAtDeliveryTime: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "REQUIREMENT_MODE_UNSPECIFIED"
      case .performedBySameVehicle: return "PERFORMED_BY_SAME_VEHICLE"
      case .inSameVehicleAtPickupTime: return "IN_SAME_VEHICLE_AT_PICKUP_TIME"
      case .inSameVehicleAtDeliveryTime: return "IN_SAME_VEHICLE_AT_DELIVERY_TIME"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RequirementMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "REQUIREMENT_MODE_UNSPECIFIED": self = .unspecified
      case "PERFORMED_BY_SAME_VEHICLE": self = .performedBySameVehicle
      case "IN_SAME_VEHICLE_AT_PICKUP_TIME": self = .inSameVehicleAtPickupTime
      case "IN_SAME_VEHICLE_AT_DELIVERY_TIME": self = .inSameVehicleAtDeliveryTime
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RequirementMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .performedBySameVehicle
      case 2: self = .inSameVehicleAtPickupTime
      case 3: self = .inSameVehicleAtDeliveryTime
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .performedBySameVehicle: return try container.encode(1)
      case .inSameVehicleAtPickupTime: return try container.encode(2)
      case .inSameVehicleAtDeliveryTime: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.ShipmentTypeRequirement"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
