// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Specifies incompatibilties between shipments depending on their
/// shipment_type. The appearance of incompatible shipments on the same route is
/// restricted based on the incompatibility mode.
public struct ShipmentTypeIncompatibility: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// List of incompatible types. Two shipments having different `shipment_types`
  /// among those listed are "incompatible".
  public var types: [Swift.String] = []

  /// Mode applied to the incompatibility.
  public var incompatibilityMode: ShipmentTypeIncompatibility.IncompatibilityMode =
    ShipmentTypeIncompatibility.IncompatibilityMode()

  /// Initialize a new instance of `ShipmentTypeIncompatibility`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ShipmentTypeIncompatibility().with { $0.types = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Modes defining how the appearance of incompatible shipments are restricted
  /// on the same route.
  public enum IncompatibilityMode: Codable, Equatable, Sendable {
    /// Unspecified incompatibility mode. This value should never be used.
    case unspecified
    /// In this mode, two shipments with incompatible types can never share the
    /// same vehicle.
    case notPerformedBySameVehicle
    /// For two shipments with incompatible types with the
    /// `NOT_IN_SAME_VEHICLE_SIMULTANEOUSLY` incompatibility mode:
    ///
    /// * If both are pickups only (no deliveries) or deliveries only (no
    ///   pickups), they cannot share the same vehicle at all.
    /// * If one of the shipments has a delivery and the other a pickup, the two
    ///   shipments can share the same vehicle iff the former shipment is
    ///   delivered before the latter is picked up.
    case notInSameVehicleSimultaneously
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .notPerformedBySameVehicle: return 1
      case .notInSameVehicleSimultaneously: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INCOMPATIBILITY_MODE_UNSPECIFIED"
      case .notPerformedBySameVehicle: return "NOT_PERFORMED_BY_SAME_VEHICLE"
      case .notInSameVehicleSimultaneously: return "NOT_IN_SAME_VEHICLE_SIMULTANEOUSLY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:IncompatibilityMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INCOMPATIBILITY_MODE_UNSPECIFIED": self = .unspecified
      case "NOT_PERFORMED_BY_SAME_VEHICLE": self = .notPerformedBySameVehicle
      case "NOT_IN_SAME_VEHICLE_SIMULTANEOUSLY": self = .notInSameVehicleSimultaneously
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:IncompatibilityMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .notPerformedBySameVehicle
      case 2: self = .notInSameVehicleSimultaneously
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .notPerformedBySameVehicle: return try container.encode(1)
      case .notInSameVehicleSimultaneously: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.ShipmentTypeIncompatibility"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
