// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A shipment model contains a set of shipments which must be performed by a
/// set of vehicles, while minimizing the overall cost, which is the sum of:
///
/// * the cost of routing the vehicles (sum of cost per total time, cost per
///   travel time, and fixed cost over all vehicles).
/// * the unperformed shipment penalties.
/// * the cost of the global duration of the shipments
public struct ShipmentModel: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Set of shipments which must be performed in the model.
  public var shipments: [Shipment] = []

  /// Set of vehicles which can be used to perform visits.
  public var vehicles: [Vehicle] = []

  /// Constrains the maximum number of active vehicles. A vehicle is active if
  /// its route performs at least one shipment. This can be used to limit the
  /// number of routes in the case where there are fewer drivers than
  /// vehicles and that the fleet of vehicles is heterogeneous. The optimization
  /// will then select the best subset of vehicles to use.
  /// Must be strictly positive.
  public var maxActiveVehicles: Swift.Int32? = nil

  /// Global start and end time of the model: no times outside of this range
  /// can be considered valid.
  ///
  /// The model's time span must be less than a year, i.e. the `global_end_time`
  /// and the `global_start_time` must be within 31536000 seconds of each other.
  ///
  /// When using `cost_per_*hour` fields, you might want to set this window to a
  /// smaller interval to increase performance (eg. if you model a single day,
  /// you should set the global time limits to that day).
  /// If unset, 00:00:00 UTC, January 1, 1970 (i.e. seconds: 0, nanos: 0) is used
  /// as default.
  public var globalStartTime: GoogleCloudWkt.Timestamp? = nil

  /// If unset, 00:00:00 UTC, January 1, 1971 (i.e. seconds: 31536000, nanos: 0)
  /// is used as default.
  public var globalEndTime: GoogleCloudWkt.Timestamp? = nil

  /// The "global duration" of the overall plan is the difference between the
  /// earliest effective start time and the latest effective end time of
  /// all vehicles. Users can assign a cost per hour to that quantity to try
  /// and optimize for earliest job completion, for example. This cost must be in
  /// the same unit as
  /// [Shipment.penalty_cost][google.cloud.optimization.v1.Shipment.penalty_cost].
  ///
  /// [google.cloud.optimization.v1.Shipment.penalty_cost]: <doc:Shipment/penaltyCost>
  public var globalDurationCostPerHour: Swift.Double = Swift.Double()

  /// Specifies duration and distance matrices used in the model. If this field
  /// is empty, Google Maps or geodesic distances will be used instead, depending
  /// on the value of the `use_geodesic_distances` field. If it is not empty,
  /// `use_geodesic_distances` cannot be true and neither
  /// `duration_distance_matrix_src_tags` nor `duration_distance_matrix_dst_tags`
  /// can be empty.
  ///
  /// Usage examples:
  ///
  /// * There are two locations: locA and locB.
  /// * 1 vehicle starting its route at locA and ending it at locA.
  /// * 1 pickup visit request at locB.
  ///
  /// ```
  /// model {
  ///   vehicles { start_tags: "locA"  end_tags: "locA" }
  ///   shipments { pickups { tags: "locB" } }
  ///   duration_distance_matrix_src_tags: "locA"
  ///   duration_distance_matrix_src_tags: "locB"
  ///   duration_distance_matrix_dst_tags: "locA"
  ///   duration_distance_matrix_dst_tags: "locB"
  ///   duration_distance_matrices {
  ///     rows {  # from: locA
  ///       durations { seconds: 0 }   meters: 0    # to: locA
  ///       durations { seconds: 100 } meters: 1000 # to: locB
  ///     }
  ///     rows {  # from: locB
  ///       durations { seconds: 102 } meters: 990 # to: locA
  ///       durations { seconds: 0 }   meters: 0   # to: locB
  ///     }
  ///   }
  /// }
  /// ```
  ///
  ///
  /// * There are three locations: locA, locB and locC.
  /// * 1 vehicle starting its route at locA and ending it at locB, using
  ///   matrix "fast".
  /// * 1 vehicle starting its route at locB and ending it at locB, using
  ///   matrix "slow".
  /// * 1 vehicle starting its route at locB and ending it at locB, using
  ///   matrix "fast".
  /// * 1 pickup visit request at locC.
  ///
  /// ```
  /// model {
  ///   vehicles { start_tags: "locA" end_tags: "locB" start_tags: "fast" }
  ///   vehicles { start_tags: "locB" end_tags: "locB" start_tags: "slow" }
  ///   vehicles { start_tags: "locB" end_tags: "locB" start_tags: "fast" }
  ///   shipments { pickups { tags: "locC" } }
  ///   duration_distance_matrix_src_tags: "locA"
  ///   duration_distance_matrix_src_tags: "locB"
  ///   duration_distance_matrix_src_tags: "locC"
  ///   duration_distance_matrix_dst_tags: "locB"
  ///   duration_distance_matrix_dst_tags: "locC"
  ///   duration_distance_matrices {
  ///     vehicle_start_tag: "fast"
  ///     rows {  # from: locA
  ///       durations { seconds: 1000 } meters: 2000 # to: locB
  ///       durations { seconds: 600 }  meters: 1000 # to: locC
  ///     }
  ///     rows {  # from: locB
  ///       durations { seconds: 0 }   meters: 0    # to: locB
  ///       durations { seconds: 700 } meters: 1200 # to: locC
  ///     }
  ///     rows {  # from: locC
  ///       durations { seconds: 702 } meters: 1190 # to: locB
  ///       durations { seconds: 0 }   meters: 0    # to: locC
  ///     }
  ///   }
  ///   duration_distance_matrices {
  ///     vehicle_start_tag: "slow"
  ///     rows {  # from: locA
  ///       durations { seconds: 1800 } meters: 2001 # to: locB
  ///       durations { seconds: 900 }  meters: 1002 # to: locC
  ///     }
  ///     rows {  # from: locB
  ///       durations { seconds: 0 }    meters: 0    # to: locB
  ///       durations { seconds: 1000 } meters: 1202 # to: locC
  ///     }
  ///     rows {  # from: locC
  ///       durations { seconds: 1001 } meters: 1195 # to: locB
  ///       durations { seconds: 0 }    meters: 0    # to: locC
  ///     }
  ///   }
  /// }
  /// ```
  public var durationDistanceMatrices: [ShipmentModel.DurationDistanceMatrix] = []

  /// Tags defining the sources of the duration and distance matrices;
  /// `duration_distance_matrices(i).rows(j)` defines durations and distances
  /// from visits with tag `duration_distance_matrix_src_tags(j)` to other visits
  /// in matrix i.
  ///
  /// Tags correspond to
  /// [VisitRequest.tags][google.cloud.optimization.v1.Shipment.VisitRequest.tags]
  /// or [Vehicle.start_tags][google.cloud.optimization.v1.Vehicle.start_tags].
  /// A given `VisitRequest` or `Vehicle` must match exactly one tag in this
  /// field. Note that a `Vehicle`'s source, destination and matrix tags may be
  /// the same; similarly a `VisitRequest`'s source and destination tags may be
  /// the same. All tags must be different and cannot be empty strings. If this
  /// field is not empty, then `duration_distance_matrices` must not be empty.
  ///
  /// [google.cloud.optimization.v1.Shipment.VisitRequest.tags]: <doc:Shipment/VisitRequest/tags>
  /// [google.cloud.optimization.v1.Vehicle.start_tags]: <doc:Vehicle/startTags>
  public var durationDistanceMatrixSrcTags: [Swift.String] = []

  /// Tags defining the destinations of the duration and distance matrices;
  /// `duration_distance_matrices(i).rows(j).durations(k)` (resp.
  /// `duration_distance_matrices(i).rows(j).meters(k))` defines the duration
  /// (resp. the distance) of the travel from visits with tag
  /// `duration_distance_matrix_src_tags(j)` to visits with tag
  /// `duration_distance_matrix_dst_tags(k)` in matrix i.
  ///
  /// Tags correspond to
  /// [VisitRequest.tags][google.cloud.optimization.v1.Shipment.VisitRequest.tags]
  /// or [Vehicle.start_tags][google.cloud.optimization.v1.Vehicle.start_tags].
  /// A given `VisitRequest` or `Vehicle` must match exactly one tag in this
  /// field. Note that a `Vehicle`'s source, destination and matrix tags may be
  /// the same; similarly a `VisitRequest`'s source and destination tags may be
  /// the same. All tags must be different and cannot be empty strings. If this
  /// field is not empty, then `duration_distance_matrices` must not be empty.
  ///
  /// [google.cloud.optimization.v1.Shipment.VisitRequest.tags]: <doc:Shipment/VisitRequest/tags>
  /// [google.cloud.optimization.v1.Vehicle.start_tags]: <doc:Vehicle/startTags>
  public var durationDistanceMatrixDstTags: [Swift.String] = []

  /// Transition attributes added to the model.
  public var transitionAttributes: [TransitionAttributes] = []

  /// Sets of incompatible shipment_types (see `ShipmentTypeIncompatibility`).
  public var shipmentTypeIncompatibilities: [ShipmentTypeIncompatibility] = []

  /// Sets of `shipment_type` requirements (see `ShipmentTypeRequirement`).
  public var shipmentTypeRequirements: [ShipmentTypeRequirement] = []

  /// Set of precedence rules which must be enforced in the model.
  public var precedenceRules: [ShipmentModel.PrecedenceRule] = []

  /// Deprecated: No longer used.
  /// Set of break rules used in the model.
  /// Each vehicle specifies the `BreakRule` that applies to it via the
  /// [Vehicle.break_rule_indices][google.cloud.optimization.v1.Vehicle.break_rule_indices]
  /// field (which must be a singleton).
  ///
  /// [google.cloud.optimization.v1.Vehicle.break_rule_indices]: <doc:Vehicle/breakRuleIndices>
  @available(*, deprecated)
  public var breakRules: [ShipmentModel.BreakRule] = []

  /// Initialize a new instance of `ShipmentModel`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ShipmentModel().with { $0.shipments = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Specifies a duration and distance matrix from visit and vehicle start
  /// locations to visit and vehicle end locations.
  public struct DurationDistanceMatrix: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Specifies the rows of the duration and distance matrix. It must have as
    /// many elements as
    /// [ShipmentModel.duration_distance_matrix_src_tags][google.cloud.optimization.v1.ShipmentModel.duration_distance_matrix_src_tags].
    ///
    /// [google.cloud.optimization.v1.ShipmentModel.duration_distance_matrix_src_tags]: <doc:ShipmentModel/durationDistanceMatrixSrcTags>
    public var rows: [ShipmentModel.DurationDistanceMatrix.Row] = []

    /// Tag defining to which vehicles this duration and distance matrix applies.
    /// If empty, this applies to all vehicles, and there can only be a single
    /// matrix.
    ///
    /// Each vehicle start must match exactly one matrix, i.e. exactly one of
    /// their `start_tags` field must match the `vehicle_start_tag` of a matrix
    /// (and of that matrix only).
    ///
    /// All matrices must have a different `vehicle_start_tag`.
    public var vehicleStartTag: Swift.String = Swift.String()

    /// Initialize a new instance of `DurationDistanceMatrix`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DurationDistanceMatrix().with { $0.rows = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Specifies a row of the duration and distance matrix.
    public struct Row: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Duration values for a given row. It must have as many elements as
      /// [ShipmentModel.duration_distance_matrix_dst_tags][google.cloud.optimization.v1.ShipmentModel.duration_distance_matrix_dst_tags].
      ///
      /// [google.cloud.optimization.v1.ShipmentModel.duration_distance_matrix_dst_tags]: <doc:ShipmentModel/durationDistanceMatrixDstTags>
      public var durations: [GoogleCloudWkt.Duration] = []

      /// Distance values for a given row. If no costs or constraints refer to
      /// distances in the model, this can be left empty; otherwise it must have
      /// as many elements as `durations`.
      public var meters: [Swift.Double] = []

      /// Initialize a new instance of `Row`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Row().with { $0.durations = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.optimization.v1.ShipmentModel.DurationDistanceMatrix.Row"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.ShipmentModel.DurationDistanceMatrix"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A precedence rule between two events (each event is the pickup or the
  /// delivery of a shipment): the "second" event has to start at least
  /// `offset_duration` after "first" has started.
  ///
  /// Several precedences can refer to the same (or related) events, e.g.,
  /// "pickup of B happens after delivery of A" and "pickup of C happens after
  /// pickup of B".
  ///
  /// Furthermore, precedences only apply when both shipments are performed and
  /// are otherwise ignored.
  public struct PrecedenceRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Shipment index of the "first" event. This field must be specified.
    public var firstIndex: Swift.Int32? = nil

    /// Indicates if the "first" event is a delivery.
    public var firstIsDelivery: Swift.Bool = Swift.Bool()

    /// Shipment index of the "second" event. This field must be specified.
    public var secondIndex: Swift.Int32? = nil

    /// Indicates if the "second" event is a delivery.
    public var secondIsDelivery: Swift.Bool = Swift.Bool()

    /// The offset between the "first" and "second" event. It can be negative.
    public var offsetDuration: GoogleCloudWkt.Duration? = nil

    /// Initialize a new instance of `PrecedenceRule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PrecedenceRule().with { $0.firstIndex = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.ShipmentModel.PrecedenceRule"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Deprecated: Use top level
  /// [BreakRule][google.cloud.optimization.v1.ShipmentModel.BreakRule] instead.
  /// Rules to generate time breaks for a vehicle (e.g. lunch
  /// breaks). A break is a contiguous period of time during which the vehicle
  /// remains idle at its current position and cannot perform any visit. A break
  /// may occur:
  ///
  /// * during the travel between two visits (which includes the time right
  ///   before or right after a visit, but not in the middle of a visit), in
  ///   which case it extends the corresponding transit time between the visits
  /// * before the vehicle start (the vehicle may not start in the middle of
  ///   a break), in which case it does not affect the vehicle start time.
  /// * after the vehicle end (ditto, with the vehicle end time).
  ///
  /// [google.cloud.optimization.v1.ShipmentModel.BreakRule]: <doc:ShipmentModel/BreakRule>
  @available(*, deprecated)
  public struct BreakRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Sequence of breaks. See the `BreakRequest` message.
    public var breakRequests: [ShipmentModel.BreakRule.BreakRequest] = []

    /// Several `FrequencyConstraint` may apply. They must all be satisfied by
    /// the `BreakRequest`s of this `BreakRule`. See `FrequencyConstraint`.
    public var frequencyConstraints: [ShipmentModel.BreakRule.FrequencyConstraint] = []

    /// Initialize a new instance of `BreakRule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BreakRule().with { $0.breakRequests = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The sequence of breaks (i.e. their number and order) that apply to each
    /// vehicle must be known beforehand. The repeated `BreakRequest`s define
    /// that sequence, in the order in which they must occur. Their time windows
    /// (`earliest_start_time` / `latest_start_time`) may overlap, but they must
    /// be compatible with the order (this is checked).
    public struct BreakRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. Lower bound (inclusive) on the start of the break.
      public var earliestStartTime: GoogleCloudWkt.Timestamp? = nil

      /// Required. Upper bound (inclusive) on the start of the break.
      public var latestStartTime: GoogleCloudWkt.Timestamp? = nil

      /// Required. Minimum duration of the break. Must be positive.
      public var minDuration: GoogleCloudWkt.Duration? = nil

      /// Initialize a new instance of `BreakRequest`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = BreakRequest().with { $0.earliestStartTime = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.optimization.v1.ShipmentModel.BreakRule.BreakRequest"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// One may further constrain the frequency and duration of the breaks
    /// specified above, by enforcing a minimum break frequency, such as
    /// "There must be a break of at least 1 hour every 12 hours". Assuming that
    /// this can be interpreted as "Within any sliding time window of 12h, there
    /// must be at least one break of at least one hour", that example would
    /// translate to the following `FrequencyConstraint`:
    /// ```
    /// {
    ///    min_break_duration { seconds: 3600 }         # 1 hour.
    ///    max_inter_break_duration { seconds: 39600 }  # 11 hours (12 - 1 = 11).
    /// }
    /// ```
    ///
    /// The timing and duration of the breaks in the solution will respect all
    /// such constraints, in addition to the time windows and minimum durations
    /// already specified in the `BreakRequest`.
    ///
    /// A `FrequencyConstraint` may in practice apply to non-consecutive breaks.
    /// For example, the following schedule honors the "1h every 12h" example:
    /// ```
    ///   04:00 vehicle start
    ///    .. performing travel and visits ..
    ///   09:00 1 hour break
    ///   10:00 end of the break
    ///    .. performing travel and visits ..
    ///   12:00 20-min lunch break
    ///   12:20 end of the break
    ///    .. performing travel and visits ..
    ///   21:00 1 hour break
    ///   22:00 end of the break
    ///    .. performing travel and visits ..
    ///   23:59 vehicle end
    /// ```
    public struct FrequencyConstraint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. Minimum break duration for this constraint. Nonnegative.
      /// See description of `FrequencyConstraint`.
      public var minBreakDuration: GoogleCloudWkt.Duration? = nil

      /// Required. Maximum allowed span of any interval of time in the route
      /// that does not include at least partially a break of `duration >=
      /// min_break_duration`. Must be positive.
      public var maxInterBreakDuration: GoogleCloudWkt.Duration? = nil

      /// Initialize a new instance of `FrequencyConstraint`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = FrequencyConstraint().with { $0.minBreakDuration = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.optimization.v1.ShipmentModel.BreakRule.FrequencyConstraint"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.ShipmentModel.BreakRule"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.ShipmentModel"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
