// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleType

/// The shipment of a single item, from one of its pickups to one of its
/// deliveries. For the shipment to be considered as performed, a unique vehicle
/// must visit one of its pickup locations (and decrease its spare capacities
/// accordingly), then visit one of its delivery locations later on (and
/// therefore re-increase its spare capacities accordingly).
public struct Shipment: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Set of pickup alternatives associated to the shipment. If not specified,
  /// the vehicle only needs to visit a location corresponding to the deliveries.
  public var pickups: [Shipment.VisitRequest] = []

  /// Set of delivery alternatives associated to the shipment. If not specified,
  /// the vehicle only needs to visit a location corresponding to the pickups.
  public var deliveries: [Shipment.VisitRequest] = []

  /// Load demands of the shipment (for example weight, volume, number of
  /// pallets etc). The keys in the map should be identifiers describing the type
  /// of the corresponding load, ideally also including the units.
  /// For example: "weight_kg", "volume_gallons", "pallet_count", etc.
  /// If a given key does not appear in the map, the corresponding load is
  /// considered as null.
  public var loadDemands: [Swift.String: Shipment.Load] = [:]

  /// If the shipment is not completed, this penalty is added to the overall
  /// cost of the routes. A shipment is considered completed if one of its pickup
  /// and delivery alternatives is visited. The cost may be expressed in the
  /// same unit used for all other cost-related fields in the model and must be
  /// positive.
  ///
  /// *IMPORTANT*: If this penalty is not specified, it is considered infinite,
  /// i.e. the shipment must be completed.
  public var penaltyCost: Swift.Double? = nil

  /// The set of vehicles that may perform this shipment. If empty, all vehicles
  /// may perform it. Vehicles are given by their index in the `ShipmentModel`'s
  /// `vehicles` list.
  public var allowedVehicleIndices: [Swift.Int32] = []

  /// Specifies the cost that is incurred when this shipment is delivered by each
  /// vehicle. If specified, it must have EITHER:
  ///
  ///   * the same number of elements as `costs_per_vehicle_indices`.
  ///     `costs_per_vehicle[i]` corresponds to vehicle
  ///     `costs_per_vehicle_indices[i]` of the model.
  ///   * the same number of elements as there are vehicles in the model. The
  ///     i-th element corresponds to vehicle #i of the model.
  ///
  /// These costs must be in the same unit as `penalty_cost` and must not be
  /// negative. Leave this field empty, if there are no such costs.
  public var costsPerVehicle: [Swift.Double] = []

  /// Indices of the vehicles to which `costs_per_vehicle` applies. If non-empty,
  /// it must have the same number of elements as `costs_per_vehicle`. A vehicle
  /// index may not be specified more than once. If a vehicle is excluded from
  /// `costs_per_vehicle_indices`, its cost is zero.
  public var costsPerVehicleIndices: [Swift.Int32] = []

  /// Specifies the maximum relative detour time compared to the shortest path
  /// from pickup to delivery. If specified, it must be nonnegative, and the
  /// shipment must contain at least a pickup and a delivery.
  ///
  /// For example, let t be the shortest time taken to go from the selected
  /// pickup alternative directly to the selected delivery alternative. Then
  /// setting `pickup_to_delivery_relative_detour_limit` enforces:
  ///
  /// ```
  /// start_time(delivery) - start_time(pickup) <=
  /// std::ceil(t * (1.0 + pickup_to_delivery_relative_detour_limit))
  /// ```
  ///
  /// If both relative and absolute limits are specified on the same shipment,
  /// the more constraining limit is used for each possible pickup/delivery pair.
  /// As of 2017/10, detours are only supported when travel durations do not
  /// depend on vehicles.
  public var pickupToDeliveryRelativeDetourLimit: Swift.Double? = nil

  /// Specifies the maximum absolute detour time compared to the shortest path
  /// from pickup to delivery. If specified, it must be nonnegative, and the
  /// shipment must contain at least a pickup and a delivery.
  ///
  /// For example, let t be the shortest time taken to go from the selected
  /// pickup alternative directly to the selected delivery alternative. Then
  /// setting `pickup_to_delivery_absolute_detour_limit` enforces:
  ///
  /// ```
  /// start_time(delivery) - start_time(pickup) <=
  /// t + pickup_to_delivery_absolute_detour_limit
  /// ```
  ///
  /// If both relative and absolute limits are specified on the same shipment,
  /// the more constraining limit is used for each possible pickup/delivery pair.
  /// As of 2017/10, detours are only supported when travel durations do not
  /// depend on vehicles.
  public var pickupToDeliveryAbsoluteDetourLimit: GoogleCloudWkt.Duration? = nil

  /// Specifies the maximum duration from start of pickup to start of delivery of
  /// a shipment. If specified, it must be nonnegative, and the shipment must
  /// contain at least a pickup and a delivery. This does not depend on which
  /// alternatives are selected for pickup and delivery, nor on vehicle speed.
  /// This can be specified alongside maximum detour constraints: the solution
  /// will respect both specifications.
  public var pickupToDeliveryTimeLimit: GoogleCloudWkt.Duration? = nil

  /// Non-empty string specifying a "type" for this shipment.
  /// This feature can be used to define incompatibilities or requirements
  /// between `shipment_types` (see `shipment_type_incompatibilities` and
  /// `shipment_type_requirements` in `ShipmentModel`).
  ///
  /// Differs from `visit_types` which is specified for a single visit: All
  /// pickup/deliveries belonging to the same shipment share the same
  /// `shipment_type`.
  public var shipmentType: Swift.String = Swift.String()

  /// Specifies a label for this shipment. This label is reported in the response
  /// in the `shipment_label` of the corresponding
  /// [ShipmentRoute.Visit][google.cloud.optimization.v1.ShipmentRoute.Visit].
  ///
  /// [google.cloud.optimization.v1.ShipmentRoute.Visit]: <doc:ShipmentRoute/Visit>
  public var label: Swift.String = Swift.String()

  /// If true, skip this shipment, but don't apply a `penalty_cost`.
  ///
  /// Ignoring a shipment results in a validation error when there are any
  /// `shipment_type_requirements` in the model.
  ///
  /// Ignoring a shipment that is performed in `injected_first_solution_routes`
  /// or `injected_solution_constraint` is permitted; the solver removes the
  /// related pickup/delivery visits from the performing route.
  /// `precedence_rules` that reference ignored shipments will also be ignored.
  public var ignore: Swift.Bool = Swift.Bool()

  /// Deprecated: Use
  /// [Shipment.load_demands][google.cloud.optimization.v1.Shipment.load_demands]
  /// instead.
  ///
  /// [google.cloud.optimization.v1.Shipment.load_demands]: <doc:Shipment/loadDemands>
  @available(*, deprecated)
  public var demands: [CapacityQuantity] = []

  /// Initialize a new instance of `Shipment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Shipment().with { $0.pickups = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Request for a visit which can be done by a vehicle: it has a geo-location
  /// (or two, see below), opening and closing times represented by time windows,
  /// and a service duration time (time spent by the vehicle once it has arrived
  /// to pickup or drop off goods).
  public struct VisitRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The geo-location where the vehicle arrives when performing this
    /// `VisitRequest`. If the shipment model has duration distance matrices,
    /// `arrival_location` must not be specified.
    public var arrivalLocation: GoogleType.LatLng? = nil

    /// The waypoint where the vehicle arrives when performing this
    /// `VisitRequest`. If the shipment model has duration distance matrices,
    /// `arrival_waypoint` must not be specified.
    public var arrivalWaypoint: Waypoint? = nil

    /// The geo-location where the vehicle departs after completing this
    /// `VisitRequest`. Can be omitted if it is the same as `arrival_location`.
    /// If the shipment model has duration distance matrices,
    /// `departure_location` must not be specified.
    public var departureLocation: GoogleType.LatLng? = nil

    /// The waypoint where the vehicle departs after completing this
    /// `VisitRequest`. Can be omitted if it is the same as `arrival_waypoint`.
    /// If the shipment model has duration distance matrices,
    /// `departure_waypoint` must not be specified.
    public var departureWaypoint: Waypoint? = nil

    /// Specifies tags attached to the visit request.
    /// Empty or duplicate strings are not allowed.
    public var tags: [Swift.String] = []

    /// Time windows which constrain the arrival time at a visit.
    /// Note that a vehicle may depart outside of the arrival time window, i.e.
    /// arrival time + duration do not need to be inside a time window. This can
    /// result in waiting time if the vehicle arrives before
    /// [TimeWindow.start_time][google.cloud.optimization.v1.TimeWindow.start_time].
    ///
    /// The absence of `TimeWindow` means that the vehicle can perform this visit
    /// at any time.
    ///
    /// Time windows must be disjoint, i.e. no time window must overlap with or
    /// be adjacent to another, and they must be in increasing order.
    ///
    /// `cost_per_hour_after_soft_end_time` and `soft_end_time` can only
    /// be set if there is a single time window.
    ///
    /// [google.cloud.optimization.v1.TimeWindow.start_time]: <doc:TimeWindow/startTime>
    public var timeWindows: [TimeWindow] = []

    /// Duration of the visit, i.e. time spent by the vehicle between arrival
    /// and departure (to be added to the possible waiting time; see
    /// `time_windows`).
    public var duration: GoogleCloudWkt.Duration? = nil

    /// Cost to service this visit request on a vehicle route. This can be used
    /// to pay different costs for each alternative pickup or delivery of a
    /// shipment. This cost must be in the same unit as `Shipment.penalty_cost`
    /// and must not be negative.
    public var cost: Swift.Double = Swift.Double()

    /// Load demands of this visit request. This is just like
    /// [Shipment.load_demands][google.cloud.optimization.v1.Shipment.load_demands]
    /// field, except that it only applies to this
    /// [VisitRequest][google.cloud.optimization.v1.Shipment.VisitRequest]
    /// instead of the whole [Shipment][google.cloud.optimization.v1.Shipment].
    /// The demands listed here are added to the demands listed in
    /// [Shipment.load_demands][google.cloud.optimization.v1.Shipment.load_demands].
    ///
    /// [google.cloud.optimization.v1.Shipment]: <doc:Shipment>
    /// [google.cloud.optimization.v1.Shipment.VisitRequest]: <doc:Shipment/VisitRequest>
    /// [google.cloud.optimization.v1.Shipment.load_demands]: <doc:Shipment/loadDemands>
    public var loadDemands: [Swift.String: Shipment.Load] = [:]

    /// Specifies the types of the visit. This may be used to allocate additional
    /// time required for a vehicle to complete this visit (see
    /// [Vehicle.extra_visit_duration_for_visit_type][google.cloud.optimization.v1.Vehicle.extra_visit_duration_for_visit_type]).
    ///
    /// A type can only appear once.
    ///
    /// [google.cloud.optimization.v1.Vehicle.extra_visit_duration_for_visit_type]: <doc:Vehicle/extraVisitDurationForVisitType>
    public var visitTypes: [Swift.String] = []

    /// Specifies a label for this `VisitRequest`. This label is reported in the
    /// response as `visit_label` in the corresponding
    /// [ShipmentRoute.Visit][google.cloud.optimization.v1.ShipmentRoute.Visit].
    ///
    /// [google.cloud.optimization.v1.ShipmentRoute.Visit]: <doc:ShipmentRoute/Visit>
    public var label: Swift.String = Swift.String()

    /// Deprecated: Use
    /// [VisitRequest.load_demands][google.cloud.optimization.v1.Shipment.VisitRequest.load_demands]
    /// instead.
    ///
    /// [google.cloud.optimization.v1.Shipment.VisitRequest.load_demands]: <doc:Shipment/VisitRequest/loadDemands>
    @available(*, deprecated)
    public var demands: [CapacityQuantity] = []

    /// Initialize a new instance of `VisitRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = VisitRequest().with { $0.arrivalLocation = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.Shipment.VisitRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// When performing a visit, a predefined amount may be added to the vehicle
  /// load if it's a pickup, or subtracted if it's a delivery. This message
  /// defines such amount. See
  /// [load_demands][google.cloud.optimization.v1.Shipment.load_demands].
  ///
  /// [google.cloud.optimization.v1.Shipment.load_demands]: <doc:Shipment/loadDemands>
  public struct Load: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The amount by which the load of the vehicle performing the corresponding
    /// visit will vary. Since it is an integer, users are advised to choose an
    /// appropriate unit to avoid loss of precision. Must be ≥ 0.
    public var amount: Swift.Int64 = Swift.Int64()

    /// Initialize a new instance of `Load`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Load().with { $0.amount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.Shipment.Load"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.Shipment"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
