// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Specifies details of unperformed shipments in a solution. For trivial cases
/// and/or if we are able to identify the cause for skipping, we report the
/// reason here.
public struct SkippedShipment: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The index corresponds to the index of the shipment in the source
  /// `ShipmentModel`.
  public var index: Swift.Int32 = Swift.Int32()

  /// Copy of the corresponding
  /// [Shipment.label][google.cloud.optimization.v1.Shipment.label], if specified
  /// in the `Shipment`.
  ///
  /// [google.cloud.optimization.v1.Shipment.label]: <doc:Shipment/label>
  public var label: Swift.String = Swift.String()

  /// A list of reasons that explain why the shipment was skipped. See comment
  /// above `Reason`.
  public var reasons: [SkippedShipment.Reason] = []

  /// Initialize a new instance of `SkippedShipment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SkippedShipment().with { $0.index = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// If we can explain why the shipment was skipped, reasons will be listed
  /// here. If the reason is not the same for all vehicles, `reason` will have
  /// more than 1 element. A skipped shipment cannot have duplicate reasons,
  /// i.e. where all fields are the same except for `example_vehicle_index`.
  /// Example:
  /// ```
  /// reasons {
  ///   code: DEMAND_EXCEEDS_VEHICLE_CAPACITY
  ///   example_vehicle_index: 1
  ///   example_exceeded_capacity_type: "Apples"
  /// }
  /// reasons {
  ///   code: DEMAND_EXCEEDS_VEHICLE_CAPACITY
  ///   example_vehicle_index: 3
  ///   example_exceeded_capacity_type: "Pears"
  /// }
  /// reasons {
  ///   code: CANNOT_BE_PERFORMED_WITHIN_VEHICLE_DISTANCE_LIMIT
  ///   example_vehicle_index: 1
  /// }
  /// ```
  /// The skipped shipment is incompatible with all vehicles. The reasons may
  /// be different for all vehicles but at least one vehicle's "Apples"
  /// capacity would be exceeded (including vehicle 1), at least one vehicle's
  /// "Pears" capacity would be exceeded (including vehicle 3) and at least one
  /// vehicle's distance limit would be exceeded (including vehicle 1).
  public struct Reason: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Refer to the comments of Code.
    public var code: SkippedShipment.Reason.Code = SkippedShipment.Reason.Code()

    /// If the reason is related to a shipment-vehicle incompatibility, this
    /// field provides the index of one relevant vehicle.
    public var exampleVehicleIndex: Swift.Int32? = nil

    /// If the reason code is `DEMAND_EXCEEDS_VEHICLE_CAPACITY`, documents one
    /// capacity type that is exceeded.
    public var exampleExceededCapacityType: Swift.String = Swift.String()

    /// Initialize a new instance of `Reason`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Reason().with { $0.code = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Code identifying the reason type. The order here is meaningless. In
    /// particular, it gives no indication of whether a given reason will
    /// appear before another in the solution, if both apply.
    public enum Code: Codable, Equatable, Sendable {
      /// This should never be used. If we are unable to understand why a
      /// shipment was skipped, we simply return an empty set of reasons.
      case unspecified
      /// There is no vehicle in the model making all shipments infeasible.
      case noVehicle
      /// The demand of the shipment exceeds a vehicle's capacity for some
      /// capacity types, one of which is `example_exceeded_capacity_type`.
      case demandExceedsVehicleCapacity
      /// The minimum distance necessary to perform this shipment, i.e. from
      /// the vehicle's `start_location` to the shipment's pickup and/or delivery
      /// locations and to the vehicle's end location exceeds the vehicle's
      /// `route_distance_limit`.
      ///
      /// Note that for this computation we use the geodesic distances.
      case cannotBePerformedWithinVehicleDistanceLimit
      /// The minimum time necessary to perform this shipment, including travel
      /// time, wait time and service time exceeds the vehicle's
      /// `route_duration_limit`.
      ///
      /// Note: travel time is computed in the best-case scenario, namely as
      /// geodesic distance x 36 m/s (roughly 130 km/hour).
      case cannotBePerformedWithinVehicleDurationLimit
      /// Same as above but we only compare minimum travel time and the
      /// vehicle's `travel_duration_limit`.
      case cannotBePerformedWithinVehicleTravelDurationLimit
      /// The vehicle cannot perform this shipment in the best-case scenario
      /// (see `CANNOT_BE_PERFORMED_WITHIN_VEHICLE_DURATION_LIMIT` for time
      /// computation) if it starts at its earliest start time: the total time
      /// would make the vehicle end after its latest end time.
      case cannotBePerformedWithinVehicleTimeWindows
      /// The `allowed_vehicle_indices` field of the shipment is not empty and
      /// this vehicle does not belong to it.
      case vehicleNotAllowed
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .noVehicle: return 1
        case .demandExceedsVehicleCapacity: return 2
        case .cannotBePerformedWithinVehicleDistanceLimit: return 3
        case .cannotBePerformedWithinVehicleDurationLimit: return 4
        case .cannotBePerformedWithinVehicleTravelDurationLimit: return 5
        case .cannotBePerformedWithinVehicleTimeWindows: return 6
        case .vehicleNotAllowed: return 7
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "CODE_UNSPECIFIED"
        case .noVehicle: return "NO_VEHICLE"
        case .demandExceedsVehicleCapacity: return "DEMAND_EXCEEDS_VEHICLE_CAPACITY"
        case .cannotBePerformedWithinVehicleDistanceLimit:
          return "CANNOT_BE_PERFORMED_WITHIN_VEHICLE_DISTANCE_LIMIT"
        case .cannotBePerformedWithinVehicleDurationLimit:
          return "CANNOT_BE_PERFORMED_WITHIN_VEHICLE_DURATION_LIMIT"
        case .cannotBePerformedWithinVehicleTravelDurationLimit:
          return "CANNOT_BE_PERFORMED_WITHIN_VEHICLE_TRAVEL_DURATION_LIMIT"
        case .cannotBePerformedWithinVehicleTimeWindows:
          return "CANNOT_BE_PERFORMED_WITHIN_VEHICLE_TIME_WINDOWS"
        case .vehicleNotAllowed: return "VEHICLE_NOT_ALLOWED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Code/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "CODE_UNSPECIFIED": self = .unspecified
        case "NO_VEHICLE": self = .noVehicle
        case "DEMAND_EXCEEDS_VEHICLE_CAPACITY": self = .demandExceedsVehicleCapacity
        case "CANNOT_BE_PERFORMED_WITHIN_VEHICLE_DISTANCE_LIMIT":
          self = .cannotBePerformedWithinVehicleDistanceLimit
        case "CANNOT_BE_PERFORMED_WITHIN_VEHICLE_DURATION_LIMIT":
          self = .cannotBePerformedWithinVehicleDurationLimit
        case "CANNOT_BE_PERFORMED_WITHIN_VEHICLE_TRAVEL_DURATION_LIMIT":
          self = .cannotBePerformedWithinVehicleTravelDurationLimit
        case "CANNOT_BE_PERFORMED_WITHIN_VEHICLE_TIME_WINDOWS":
          self = .cannotBePerformedWithinVehicleTimeWindows
        case "VEHICLE_NOT_ALLOWED": self = .vehicleNotAllowed
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Code/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .noVehicle
        case 2: self = .demandExceedsVehicleCapacity
        case 3: self = .cannotBePerformedWithinVehicleDistanceLimit
        case 4: self = .cannotBePerformedWithinVehicleDurationLimit
        case 5: self = .cannotBePerformedWithinVehicleTravelDurationLimit
        case 6: self = .cannotBePerformedWithinVehicleTimeWindows
        case 7: self = .vehicleNotAllowed
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .noVehicle: return try container.encode(1)
        case .demandExceedsVehicleCapacity: return try container.encode(2)
        case .cannotBePerformedWithinVehicleDistanceLimit: return try container.encode(3)
        case .cannotBePerformedWithinVehicleDurationLimit: return try container.encode(4)
        case .cannotBePerformedWithinVehicleTravelDurationLimit: return try container.encode(5)
        case .cannotBePerformedWithinVehicleTimeWindows: return try container.encode(6)
        case .vehicleNotAllowed: return try container.encode(7)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.SkippedShipment.Reason"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.SkippedShipment"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
