// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Time windows constrain the time of an event, such as the arrival time at a
/// visit, or the start and end time of a vehicle.
///
/// Hard time window bounds, `start_time` and `end_time`, enforce the earliest
/// and latest time of the event, such that `start_time <= event_time <=
/// end_time`. The soft time window lower bound, `soft_start_time`, expresses a
/// preference for the event to happen at or after `soft_start_time` by incurring
/// a cost proportional to how long before soft_start_time the event occurs. The
/// soft time window upper bound, `soft_end_time`, expresses a preference for the
/// event to happen at or before `soft_end_time` by incurring a cost proportional
/// to how long after `soft_end_time` the event occurs. `start_time`, `end_time`,
/// `soft_start_time` and `soft_end_time` should be within the global time limits
/// (see
/// [ShipmentModel.global_start_time][google.cloud.optimization.v1.ShipmentModel.global_start_time]
/// and
/// [ShipmentModel.global_end_time][google.cloud.optimization.v1.ShipmentModel.global_end_time])
/// and should respect:
/// ```
///   0 <= `start_time` <= `soft_start_time` <= `end_time` and
///   0 <= `start_time` <= `soft_end_time` <= `end_time`.
/// ```
///
/// [google.cloud.optimization.v1.ShipmentModel.global_end_time]: <doc:ShipmentModel/globalEndTime>
/// [google.cloud.optimization.v1.ShipmentModel.global_start_time]: <doc:ShipmentModel/globalStartTime>
public struct TimeWindow: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The hard time window start time. If unspecified it will be set to
  /// `ShipmentModel.global_start_time`.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// The hard time window end time. If unspecified it will be set to
  /// `ShipmentModel.global_end_time`.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// The soft start time of the time window.
  public var softStartTime: GoogleCloudWkt.Timestamp? = nil

  /// The soft end time of the time window.
  public var softEndTime: GoogleCloudWkt.Timestamp? = nil

  /// A cost per hour added to other costs in the model if the event occurs
  /// before soft_start_time, computed as:
  ///
  /// ```
  ///    max(0, soft_start_time - t.seconds)
  ///                           * cost_per_hour_before_soft_start_time / 3600,
  /// t being the time of the event.
  /// ```
  ///
  /// This cost must be positive, and the field can only be set if
  /// soft_start_time has been set.
  public var costPerHourBeforeSoftStartTime: Swift.Double? = nil

  /// A cost per hour added to other costs in the model if the event occurs after
  /// `soft_end_time`, computed as:
  ///
  /// ```
  ///    max(0, t.seconds - soft_end_time.seconds)
  ///                     * cost_per_hour_after_soft_end_time / 3600,
  /// t being the time of the event.
  /// ```
  ///
  /// This cost must be positive, and the field can only be set if
  /// `soft_end_time` has been set.
  public var costPerHourAfterSoftEndTime: Swift.Double? = nil

  /// Initialize a new instance of `TimeWindow`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimeWindow().with { $0.startTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.TimeWindow"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
