// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Specifies attributes of transitions between two consecutive visits on a
/// route. Several `TransitionAttributes` may apply to the same transition: in
/// that case, all extra costs add up and the strictest constraint or limit
/// applies (following natural "AND" semantics).
public struct TransitionAttributes: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Tags defining the set of (src->dst) transitions these attributes apply to.
  ///
  /// A source visit or vehicle start matches iff its
  /// [VisitRequest.tags][google.cloud.optimization.v1.Shipment.VisitRequest.tags]
  /// or [Vehicle.start_tags][google.cloud.optimization.v1.Vehicle.start_tags]
  /// either contains `src_tag` or does not contain `excluded_src_tag` (depending
  /// on which of these two fields is non-empty).
  ///
  /// [google.cloud.optimization.v1.Shipment.VisitRequest.tags]: <doc:Shipment/VisitRequest/tags>
  /// [google.cloud.optimization.v1.Vehicle.start_tags]: <doc:Vehicle/startTags>
  public var srcTag: Swift.String = Swift.String()

  /// See `src_tag`. Exactly one of `src_tag` and `excluded_src_tag` must be
  /// non-empty.
  public var excludedSrcTag: Swift.String = Swift.String()

  /// A destination visit or vehicle end matches iff its
  /// [VisitRequest.tags][google.cloud.optimization.v1.Shipment.VisitRequest.tags]
  /// or [Vehicle.end_tags][google.cloud.optimization.v1.Vehicle.end_tags] either
  /// contains `dst_tag` or does not contain `excluded_dst_tag` (depending on
  /// which of these two fields is non-empty).
  ///
  /// [google.cloud.optimization.v1.Shipment.VisitRequest.tags]: <doc:Shipment/VisitRequest/tags>
  /// [google.cloud.optimization.v1.Vehicle.end_tags]: <doc:Vehicle/endTags>
  public var dstTag: Swift.String = Swift.String()

  /// See `dst_tag`. Exactly one of `dst_tag` and `excluded_dst_tag` must be
  /// non-empty.
  public var excludedDstTag: Swift.String = Swift.String()

  /// Specifies a cost for performing this transition. This is in the same unit
  /// as all other costs in the model and must not be negative. It is applied on
  /// top of all other existing costs.
  public var cost: Swift.Double = Swift.Double()

  /// Specifies a cost per kilometer applied to the distance traveled while
  /// performing this transition. It adds up to any
  /// [Vehicle.cost_per_kilometer][google.cloud.optimization.v1.Vehicle.cost_per_kilometer]
  /// specified on vehicles.
  ///
  /// [google.cloud.optimization.v1.Vehicle.cost_per_kilometer]: <doc:Vehicle/costPerKilometer>
  public var costPerKilometer: Swift.Double = Swift.Double()

  /// Specifies a limit on the distance traveled while performing this
  /// transition.
  ///
  /// As of 2021/06, only soft limits are supported.
  public var distanceLimit: DistanceLimit? = nil

  /// Specifies a delay incurred when performing this transition.
  ///
  /// This delay always occurs *after* finishing the source visit and *before*
  /// starting the destination visit.
  public var delay: GoogleCloudWkt.Duration? = nil

  /// Initialize a new instance of `TransitionAttributes`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransitionAttributes().with { $0.srcTag = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.TransitionAttributes"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
