// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleType

/// Models a vehicle in a shipment problem. Solving a shipment problem will
/// build a route starting from `start_location` and ending at `end_location`
/// for this vehicle. A route is a sequence of visits (see `ShipmentRoute`).
public struct Vehicle: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The travel mode which affects the roads usable by the vehicle and its
  /// speed. See also `travel_duration_multiple`.
  public var travelMode: Vehicle.TravelMode = Vehicle.TravelMode()

  /// Optional. A set of conditions to satisfy that affect the way routes are
  /// calculated for the given vehicle.
  public var routeModifiers: RouteModifiers? = nil

  /// Geographic location where the vehicle starts before picking up any
  /// shipments. If not specified, the vehicle starts at its first pickup.
  /// If the shipment model has duration and distance matrices, `start_location`
  /// must not be specified.
  public var startLocation: GoogleType.LatLng? = nil

  /// Waypoint representing a geographic location where the vehicle starts before
  /// picking up any shipments. If neither `start_waypoint` nor `start_location`
  /// is specified, the vehicle starts at its first pickup.
  /// If the shipment model has duration and distance matrices, `start_waypoint`
  /// must not be specified.
  public var startWaypoint: Waypoint? = nil

  /// Geographic location where the vehicle ends after it has completed its last
  /// `VisitRequest`. If not specified the vehicle's `ShipmentRoute` ends
  /// immediately when it completes its last `VisitRequest`.
  /// If the shipment model has duration and distance matrices, `end_location`
  /// must not be specified.
  public var endLocation: GoogleType.LatLng? = nil

  /// Waypoint representing a geographic location where the vehicle ends after
  /// it has completed its last `VisitRequest`. If neither `end_waypoint` nor
  /// `end_location` is specified, the vehicle's `ShipmentRoute` ends immediately
  /// when it completes its last `VisitRequest`.
  /// If the shipment model has duration and distance matrices, `end_waypoint`
  /// must not be specified.
  public var endWaypoint: Waypoint? = nil

  /// Specifies tags attached to the start of the vehicle's route.
  ///
  /// Empty or duplicate strings are not allowed.
  public var startTags: [Swift.String] = []

  /// Specifies tags attached to the end of the vehicle's route.
  ///
  /// Empty or duplicate strings are not allowed.
  public var endTags: [Swift.String] = []

  /// Time windows during which the vehicle may depart its start location.
  /// They must be within the global time limits (see
  /// [ShipmentModel.global_*][google.cloud.optimization.v1.ShipmentModel.global_start_time]
  /// fields). If unspecified, there is no limitation besides those global time
  /// limits.
  ///
  /// Time windows belonging to the same repeated field must be disjoint, i.e. no
  /// time window can overlap with or be adjacent to another, and they must be in
  /// chronological order.
  ///
  /// `cost_per_hour_after_soft_end_time` and `soft_end_time` can only be set if
  /// there is a single time window.
  ///
  /// [google.cloud.optimization.v1.ShipmentModel.global_start_time]: <doc:ShipmentModel/globalStartTime>
  public var startTimeWindows: [TimeWindow] = []

  /// Time windows during which the vehicle may arrive at its end location.
  /// They must be within the global time limits (see
  /// [ShipmentModel.global_*][google.cloud.optimization.v1.ShipmentModel.global_start_time]
  /// fields). If unspecified, there is no limitation besides those global time
  /// limits.
  ///
  /// Time windows belonging to the same repeated field must be disjoint, i.e. no
  /// time window can overlap with or be adjacent to another, and they must be in
  /// chronological order.
  ///
  /// `cost_per_hour_after_soft_end_time` and `soft_end_time` can only be set if
  /// there is a single time window.
  ///
  /// [google.cloud.optimization.v1.ShipmentModel.global_start_time]: <doc:ShipmentModel/globalStartTime>
  public var endTimeWindows: [TimeWindow] = []

  /// Specifies a multiplicative factor that can be used to increase or decrease
  /// travel times of this vehicle. For example, setting this to 2.0 means
  /// that this vehicle is slower and has travel times that are twice what they
  /// are for standard vehicles. This multiple does not affect visit durations.
  /// It does affect cost if `cost_per_hour` or `cost_per_traveled_hour` are
  /// specified. This must be in the range [0.001, 1000.0]. If unset, the vehicle
  /// is standard, and this multiple is considered 1.0.
  ///
  /// WARNING: Travel times will be rounded to the nearest second after this
  /// multiple is applied but before performing any numerical operations, thus,
  /// a small multiple may result in a loss of precision.
  ///
  /// See also `extra_visit_duration_for_visit_type` below.
  public var travelDurationMultiple: Swift.Double? = nil

  /// Unloading policy enforced on the vehicle.
  public var unloadingPolicy: Vehicle.UnloadingPolicy = Vehicle.UnloadingPolicy()

  /// Capacities of the vehicle (weight, volume, # of pallets for example).
  /// The keys in the map are the identifiers of the type of load, consistent
  /// with the keys of the
  /// [Shipment.load_demands][google.cloud.optimization.v1.Shipment.load_demands]
  /// field. If a given key is absent from this map, the corresponding capacity
  /// is considered to be limitless.
  ///
  /// [google.cloud.optimization.v1.Shipment.load_demands]: <doc:Shipment/loadDemands>
  public var loadLimits: [Swift.String: Vehicle.LoadLimit] = [:]

  /// Vehicle costs: all costs add up and must be in the same unit as
  /// [Shipment.penalty_cost][google.cloud.optimization.v1.Shipment.penalty_cost].
  ///
  /// Cost per hour of the vehicle route. This cost is applied to the total time
  /// taken by the route, and includes travel time, waiting time, and visit time.
  /// Using `cost_per_hour` instead of just `cost_per_traveled_hour` may result
  /// in additional latency.
  ///
  /// [google.cloud.optimization.v1.Shipment.penalty_cost]: <doc:Shipment/penaltyCost>
  public var costPerHour: Swift.Double = Swift.Double()

  /// Cost per traveled hour of the vehicle route. This cost is applied only to
  /// travel time taken by the route (i.e., that reported in
  /// [ShipmentRoute.transitions][google.cloud.optimization.v1.ShipmentRoute.transitions]),
  /// and excludes waiting time and visit time.
  ///
  /// [google.cloud.optimization.v1.ShipmentRoute.transitions]: <doc:ShipmentRoute/transitions>
  public var costPerTraveledHour: Swift.Double = Swift.Double()

  /// Cost per kilometer of the vehicle route. This cost is applied to the
  /// distance reported in the
  /// [ShipmentRoute.transitions][google.cloud.optimization.v1.ShipmentRoute.transitions]
  /// and does not apply to any distance implicitly traveled from the
  /// `arrival_location` to the `departure_location` of a single `VisitRequest`.
  ///
  /// [google.cloud.optimization.v1.ShipmentRoute.transitions]: <doc:ShipmentRoute/transitions>
  public var costPerKilometer: Swift.Double = Swift.Double()

  /// Fixed cost applied if this vehicle is used to handle a shipment.
  public var fixedCost: Swift.Double = Swift.Double()

  /// This field only applies to vehicles when their route does not serve any
  /// shipments. It indicates if the vehicle should be considered as used or not
  /// in this case.
  ///
  /// If true, the vehicle goes from its start to its end location even if it
  /// doesn't serve any shipments, and time and distance costs resulting from its
  /// start --> end travel are taken into account.
  ///
  /// Otherwise, it doesn't travel from its start to its end location, and no
  /// `break_rule` or delay (from `TransitionAttributes`) are scheduled for this
  /// vehicle. In this case, the vehicle's `ShipmentRoute` doesn't contain any
  /// information except for the vehicle index and label.
  public var usedIfRouteIsEmpty: Swift.Bool = Swift.Bool()

  /// Limit applied to the total duration of the vehicle's route. In a given
  /// `OptimizeToursResponse`, the route duration of a vehicle is the
  /// difference between its `vehicle_end_time` and `vehicle_start_time`.
  public var routeDurationLimit: Vehicle.DurationLimit? = nil

  /// Limit applied to the travel duration of the vehicle's route. In a given
  /// `OptimizeToursResponse`, the route travel duration is the sum of all its
  /// [transitions.travel_duration][google.cloud.optimization.v1.ShipmentRoute.Transition.travel_duration].
  ///
  /// [google.cloud.optimization.v1.ShipmentRoute.Transition.travel_duration]: <doc:ShipmentRoute/Transition/travelDuration>
  public var travelDurationLimit: Vehicle.DurationLimit? = nil

  /// Limit applied to the total distance of the vehicle's route. In a given
  /// `OptimizeToursResponse`, the route distance is the sum of all its
  /// [transitions.travel_distance_meters][google.cloud.optimization.v1.ShipmentRoute.Transition.travel_distance_meters].
  ///
  /// [google.cloud.optimization.v1.ShipmentRoute.Transition.travel_distance_meters]: <doc:ShipmentRoute/Transition/travelDistanceMeters>
  public var routeDistanceLimit: DistanceLimit? = nil

  /// Specifies a map from visit_types strings to durations. The duration is time
  /// in addition to
  /// [VisitRequest.duration][google.cloud.optimization.v1.Shipment.VisitRequest.duration]
  /// to be taken at visits with the specified `visit_types`. This extra visit
  /// duration adds cost if `cost_per_hour` is specified. Keys (i.e.
  /// `visit_types`) cannot be empty strings.
  ///
  /// If a visit request has multiple types, a duration will be added for each
  /// type in the map.
  ///
  /// [google.cloud.optimization.v1.Shipment.VisitRequest.duration]: <doc:Shipment/VisitRequest/duration>
  public var extraVisitDurationForVisitType: [Swift.String: GoogleCloudWkt.Duration] = [:]

  /// Describes the break schedule to be enforced on this vehicle.
  /// If empty, no breaks will be scheduled for this vehicle.
  public var breakRule: BreakRule? = nil

  /// Specifies a label for this vehicle. This label is reported in the response
  /// as the `vehicle_label` of the corresponding
  /// [ShipmentRoute][google.cloud.optimization.v1.ShipmentRoute].
  ///
  /// [google.cloud.optimization.v1.ShipmentRoute]: <doc:ShipmentRoute>
  public var label: Swift.String = Swift.String()

  /// If true, `used_if_route_is_empty` must be false, and this vehicle will
  /// remain unused.
  ///
  /// If a shipment is performed by an ignored vehicle in
  /// `injected_first_solution_routes`, it is skipped in the first solution but
  /// is free to be performed in the response.
  ///
  /// If a shipment is performed by an ignored vehicle in
  /// `injected_solution_constraint` and any related pickup/delivery is
  /// constrained to remain on the vehicle (i.e., not relaxed to level
  /// `RELAX_ALL_AFTER_THRESHOLD`), it is skipped in the response.
  /// If a shipment has a non-empty `allowed_vehicle_indices` field and all of
  /// the allowed vehicles are ignored, it is skipped in the response.
  public var ignore: Swift.Bool = Swift.Bool()

  /// Deprecated: No longer used.
  /// Indices in the `break_rule` field in the source
  /// [ShipmentModel][google.cloud.optimization.v1.ShipmentModel]. They
  /// correspond to break rules enforced on the vehicle.
  ///
  /// As of 2018/03, at most one rule index per vehicle can be specified.
  ///
  /// [google.cloud.optimization.v1.ShipmentModel]: <doc:ShipmentModel>
  @available(*, deprecated)
  public var breakRuleIndices: [Swift.Int32] = []

  /// Deprecated: Use
  /// [Vehicle.load_limits][google.cloud.optimization.v1.Vehicle.load_limits]
  /// instead.
  ///
  /// [google.cloud.optimization.v1.Vehicle.load_limits]: <doc:Vehicle/loadLimits>
  @available(*, deprecated)
  public var capacities: [CapacityQuantity] = []

  /// Deprecated: Use
  /// [Vehicle.LoadLimit.start_load_interval][google.cloud.optimization.v1.Vehicle.LoadLimit.start_load_interval]
  /// instead.
  ///
  /// [google.cloud.optimization.v1.Vehicle.LoadLimit.start_load_interval]: <doc:Vehicle/LoadLimit/startLoadInterval>
  @available(*, deprecated)
  public var startLoadIntervals: [CapacityQuantityInterval] = []

  /// Deprecated: Use
  /// [Vehicle.LoadLimit.end_load_interval][google.cloud.optimization.v1.Vehicle.LoadLimit.end_load_interval]
  /// instead.
  ///
  /// [google.cloud.optimization.v1.Vehicle.LoadLimit.end_load_interval]: <doc:Vehicle/LoadLimit/endLoadInterval>
  @available(*, deprecated)
  public var endLoadIntervals: [CapacityQuantityInterval] = []

  /// Initialize a new instance of `Vehicle`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Vehicle().with { $0.travelMode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Defines a load limit applying to a vehicle, e.g. "this truck may only
  /// carry up to 3500 kg". See
  /// [load_limits][google.cloud.optimization.v1.Vehicle.load_limits].
  ///
  /// [google.cloud.optimization.v1.Vehicle.load_limits]: <doc:Vehicle/loadLimits>
  public struct LoadLimit: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The maximum acceptable amount of load.
    public var maxLoad: Swift.Int64? = nil

    /// A soft limit of the load. See
    /// [cost_per_unit_above_soft_max][google.cloud.optimization.v1.Vehicle.LoadLimit.cost_per_unit_above_soft_max].
    ///
    /// [google.cloud.optimization.v1.Vehicle.LoadLimit.cost_per_unit_above_soft_max]: <doc:Vehicle/LoadLimit/costPerUnitAboveSoftMax>
    public var softMaxLoad: Swift.Int64 = Swift.Int64()

    /// If the load ever exceeds
    /// [soft_max_load][google.cloud.optimization.v1.Vehicle.LoadLimit.soft_max_load]
    /// along this vehicle's route, the following cost penalty applies (only once
    /// per vehicle): (load -
    /// [soft_max_load][google.cloud.optimization.v1.Vehicle.LoadLimit.soft_max_load])
    /// * [cost_per_unit_above_soft_max][google.cloud.optimization.v1.Vehicle.LoadLimit.cost_per_unit_above_soft_max]. All costs
    /// add up and must be in the same unit as
    /// [Shipment.penalty_cost][google.cloud.optimization.v1.Shipment.penalty_cost].
    ///
    /// [google.cloud.optimization.v1.Shipment.penalty_cost]: <doc:Shipment/penaltyCost>
    /// [google.cloud.optimization.v1.Vehicle.LoadLimit.cost_per_unit_above_soft_max]: <doc:Vehicle/LoadLimit/costPerUnitAboveSoftMax>
    /// [google.cloud.optimization.v1.Vehicle.LoadLimit.soft_max_load]: <doc:Vehicle/LoadLimit/softMaxLoad>
    public var costPerUnitAboveSoftMax: Swift.Double = Swift.Double()

    /// The acceptable load interval of the vehicle at the start of the route.
    public var startLoadInterval: Vehicle.LoadLimit.Interval? = nil

    /// The acceptable load interval of the vehicle at the end of the route.
    public var endLoadInterval: Vehicle.LoadLimit.Interval? = nil

    /// Initialize a new instance of `LoadLimit`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LoadLimit().with { $0.maxLoad = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Interval of acceptable load amounts.
    public struct Interval: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// A minimum acceptable load. Must be ≥ 0.
      /// If they're both specified,
      /// [min][google.cloud.optimization.v1.Vehicle.LoadLimit.Interval.min] must
      /// be ≤
      /// [max][google.cloud.optimization.v1.Vehicle.LoadLimit.Interval.max].
      ///
      /// [google.cloud.optimization.v1.Vehicle.LoadLimit.Interval.max]: <doc:Vehicle/LoadLimit/Interval/max>
      /// [google.cloud.optimization.v1.Vehicle.LoadLimit.Interval.min]: <doc:Vehicle/LoadLimit/Interval/min>
      public var min: Swift.Int64 = Swift.Int64()

      /// A maximum acceptable load. Must be ≥ 0. If unspecified, the maximum
      /// load is unrestricted by this message.
      /// If they're both specified,
      /// [min][google.cloud.optimization.v1.Vehicle.LoadLimit.Interval.min] must
      /// be ≤
      /// [max][google.cloud.optimization.v1.Vehicle.LoadLimit.Interval.max].
      ///
      /// [google.cloud.optimization.v1.Vehicle.LoadLimit.Interval.max]: <doc:Vehicle/LoadLimit/Interval/max>
      /// [google.cloud.optimization.v1.Vehicle.LoadLimit.Interval.min]: <doc:Vehicle/LoadLimit/Interval/min>
      public var max: Swift.Int64? = nil

      /// Initialize a new instance of `Interval`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Interval().with { $0.min = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.optimization.v1.Vehicle.LoadLimit.Interval"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.Vehicle.LoadLimit"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A limit defining a maximum duration of the route of a vehicle. It can be
  /// either hard or soft.
  ///
  /// When a soft limit field is defined, both the soft max threshold and its
  /// associated cost must be defined together.
  public struct DurationLimit: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// A hard limit constraining the duration to be at most max_duration.
    public var maxDuration: GoogleCloudWkt.Duration? = nil

    /// A soft limit not enforcing a maximum duration limit, but when violated
    /// makes the route incur a cost. This cost adds up to other costs defined in
    /// the model, with the same unit.
    ///
    /// If defined, `soft_max_duration` must be nonnegative. If max_duration is
    /// also defined, `soft_max_duration` must be less than max_duration.
    public var softMaxDuration: GoogleCloudWkt.Duration? = nil

    /// Cost per hour incurred if the `soft_max_duration` threshold is violated.
    /// The additional cost is 0 if the duration is under the threshold,
    /// otherwise the cost depends on the duration as follows:
    /// ```
    ///   cost_per_hour_after_soft_max * (duration - soft_max_duration)
    /// ```
    /// The cost must be nonnegative.
    public var costPerHourAfterSoftMax: Swift.Double? = nil

    /// A soft limit not enforcing a maximum duration limit, but when violated
    /// makes the route incur a cost, quadratic in the duration. This cost adds
    /// up to other costs defined in the model, with the same unit.
    ///
    /// If defined, `quadratic_soft_max_duration` must be nonnegative. If
    /// `max_duration` is also defined, `quadratic_soft_max_duration` must be
    /// less than `max_duration`, and the difference must be no larger than one
    /// day:
    ///
    ///    `max_duration - quadratic_soft_max_duration <= 86400 seconds`
    public var quadraticSoftMaxDuration: GoogleCloudWkt.Duration? = nil

    /// Cost per square hour incurred if the
    /// `quadratic_soft_max_duration` threshold is violated.
    ///
    /// The additional cost is 0 if the duration is under the threshold,
    /// otherwise the cost depends on the duration as follows:
    ///
    /// ```
    ///   cost_per_square_hour_after_quadratic_soft_max *
    ///   (duration - quadratic_soft_max_duration)^2
    /// ```
    ///
    /// The cost must be nonnegative.
    public var costPerSquareHourAfterQuadraticSoftMax: Swift.Double? = nil

    /// Initialize a new instance of `DurationLimit`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DurationLimit().with { $0.maxDuration = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.optimization.v1.Vehicle.DurationLimit"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Travel modes which can be used by vehicles.
  ///
  /// These should be a subset of the Google Maps Platform Routes Preferred API
  /// travel modes, see:
  /// https://developers.google.com/maps/documentation/routes_preferred/reference/rest/Shared.Types/RouteTravelMode.
  public enum TravelMode: Codable, Equatable, Sendable {
    /// Unspecified travel mode, equivalent to `DRIVING`.
    case unspecified
    /// Travel mode corresponding to driving directions (car, ...).
    case driving
    /// Travel mode corresponding to walking directions.
    case walking
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .driving: return 1
      case .walking: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TRAVEL_MODE_UNSPECIFIED"
      case .driving: return "DRIVING"
      case .walking: return "WALKING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TravelMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TRAVEL_MODE_UNSPECIFIED": self = .unspecified
      case "DRIVING": self = .driving
      case "WALKING": self = .walking
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TravelMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .driving
      case 2: self = .walking
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .driving: return try container.encode(1)
      case .walking: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Policy on how a vehicle can be unloaded. Applies only to shipments having
  /// both a pickup and a delivery.
  ///
  /// Other shipments are free to occur anywhere on the route independent of
  /// `unloading_policy`.
  public enum UnloadingPolicy: Codable, Equatable, Sendable {
    /// Unspecified unloading policy; deliveries must just occur after their
    /// corresponding pickups.
    case unspecified
    /// Deliveries must occur in reverse order of pickups
    case lastInFirstOut
    /// Deliveries must occur in the same order as pickups
    case firstInFirstOut
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .lastInFirstOut: return 1
      case .firstInFirstOut: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "UNLOADING_POLICY_UNSPECIFIED"
      case .lastInFirstOut: return "LAST_IN_FIRST_OUT"
      case .firstInFirstOut: return "FIRST_IN_FIRST_OUT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:UnloadingPolicy/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNLOADING_POLICY_UNSPECIFIED": self = .unspecified
      case "LAST_IN_FIRST_OUT": self = .lastInFirstOut
      case "FIRST_IN_FIRST_OUT": self = .firstInFirstOut
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:UnloadingPolicy/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .lastInFirstOut
      case 2: self = .firstInFirstOut
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .lastInFirstOut: return try container.encode(1)
      case .firstInFirstOut: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.Vehicle"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
