// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Encapsulates a waypoint. Waypoints mark arrival and departure locations of
/// VisitRequests, and start and end locations of Vehicles.
public struct Waypoint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Indicates that the location of this waypoint is meant to have a preference
  /// for the vehicle to stop at a particular side of road. When you set this
  /// value, the route will pass through the location so that the vehicle can
  /// stop at the side of road that the location is biased towards from the
  /// center of the road. This option works only for the 'DRIVING' travel mode,
  /// and when the 'location_type' is set to 'location'.
  public var sideOfRoad: Swift.Bool = Swift.Bool()

  /// Different ways to represent a location.
  public var locationType: OneOf_LocationType? = nil

  /// Initialize a new instance of `Waypoint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Waypoint().with { $0.location = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case location = "location"
    case placeId = "placeId"
    case sideOfRoad = "sideOfRoad"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.sideOfRoad = try container.decode(Swift.Bool.self, forKey: .sideOfRoad)

    var locationType: OneOf_LocationType? = nil
    let locationTypeCheckAndSet = {
      if locationType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'locationType'"))
      }
      locationType = $0
    }
    if let location = try container.decodeIfPresent(Location?.self, forKey: .location) {
      try locationTypeCheckAndSet(.location(location))
    }
    if let placeId = try container.decodeIfPresent(Swift.String.self, forKey: .placeId) {
      try locationTypeCheckAndSet(.placeId(placeId))
    }
    self.locationType = locationType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.sideOfRoad, forKey: .sideOfRoad)

    if let choice = self.locationType {
      switch choice {
      case .location(let value):
        try container.encode(value, forKey: .location)
      case .placeId(let value):
        try container.encode(value, forKey: .placeId)
      }
    }
  }

  /// Different ways to represent a location.
  public enum OneOf_LocationType: Codable, Equatable, Sendable {
    /// A point specified using geographic coordinates, including an optional
    /// heading.
    indirect case location(Location?)
    /// The POI Place ID associated with the waypoint.
    case placeId(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.optimization.v1.Waypoint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
